package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AreaNegocio generated by hbm2java
 */
public class AreaNegocio  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Rubro> rubros = new HashSet<Rubro>(0);

    public AreaNegocio() {
    }

	
    public AreaNegocio(String nombre) {
        this.nombre = nombre;
    }
    public AreaNegocio(String nombre, Set<Rubro> rubros) {
       this.nombre = nombre;
       this.rubros = rubros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Rubro> getRubros() {
        return this.rubros;
    }
    
    public void setRubros(Set<Rubro> rubros) {
        this.rubros = rubros;
    }




}


