package entidades;
// Generated 15 ene. 2022 13:01:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BalanceEfectivo generated by hbm2java
 */
public class BalanceEfectivo  implements java.io.Serializable {


     private Integer id;
     private Balance balance;
     private Date fecha;
     private char turno;
     private BigDecimal valor;
     private String referencia;

    public BalanceEfectivo() {
    }

	
    public BalanceEfectivo(Balance balance, Date fecha, char turno, BigDecimal valor) {
        this.balance = balance;
        this.fecha = fecha;
        this.turno = turno;
        this.valor = valor;
    }
    public BalanceEfectivo(Balance balance, Date fecha, char turno, BigDecimal valor, String referencia) {
       this.balance = balance;
       this.fecha = fecha;
       this.turno = turno;
       this.valor = valor;
       this.referencia = referencia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balance getBalance() {
        return this.balance;
    }
    
    public void setBalance(Balance balance) {
        this.balance = balance;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public char getTurno() {
        return this.turno;
    }
    
    public void setTurno(char turno) {
        this.turno = turno;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }




}


