package entidades;
// Generated 21 ene. 2022 15:27:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BalanceGastoPersonal generated by hbm2java
 */
public class BalanceGastoPersonal  implements java.io.Serializable {


     private Integer id;
     private Balance balance;
     private Empleado empleado= new Empleado();
     private TipoGasto tipoGasto= new TipoGasto();
     private Date fecha;
     private BigDecimal valor;
     private String observaciones;

    public BalanceGastoPersonal() {
    }

	
    public BalanceGastoPersonal(Balance balance, TipoGasto tipoGasto, Date fecha, BigDecimal valor) {
        this.balance = balance;
        this.tipoGasto = tipoGasto;
        this.fecha = fecha;
        this.valor = valor;
    }
    public BalanceGastoPersonal(Balance balance, Empleado empleado, TipoGasto tipoGasto, Date fecha, BigDecimal valor, String observaciones) {
       this.balance = balance;
       this.empleado = empleado;
       this.tipoGasto = tipoGasto;
       this.fecha = fecha;
       this.valor = valor;
       this.observaciones = observaciones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balance getBalance() {
        return this.balance;
    }
    
    public void setBalance(Balance balance) {
        this.balance = balance;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public TipoGasto getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(TipoGasto tipoGasto) {
        this.tipoGasto = tipoGasto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


