package entidades;
// Generated 3 ene. 2022 16:12:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BalanceIngreso generated by hbm2java
 */
public class BalanceIngreso  implements java.io.Serializable {


     private Integer id;
     private Balance balance;
     private Producto producto= new Producto();
     private Proveedor proveedor= new Proveedor();
     private Unidad unidad= new Unidad();
     private Date fecha;
     private BigDecimal cantidad;
     private BigDecimal precioUnitario;
     private BigDecimal precioTotal;

    public BalanceIngreso() {
    }

	
    public BalanceIngreso(Balance balance, Producto producto, Unidad unidad, BigDecimal cantidad, BigDecimal precioUnitario, BigDecimal precioTotal) {
        this.balance = balance;
        this.producto = producto;
        this.unidad = unidad;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.precioTotal = precioTotal;
    }
    public BalanceIngreso(Balance balance, Producto producto, Proveedor proveedor, Unidad unidad, BigDecimal cantidad, BigDecimal precioUnitario, BigDecimal precioTotal) {
       this.balance = balance;
       this.producto = producto;
       this.proveedor = proveedor;
       this.unidad = unidad;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.precioTotal = precioTotal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balance getBalance() {
        return this.balance;
    }
    
    public void setBalance(Balance balance) {
        this.balance = balance;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public BigDecimal getPrecioTotal() {
        return this.precioTotal;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    public void setPrecioTotal(BigDecimal precioTotal) {
        this.precioTotal = precioTotal;
    }

    public double getCantidadDouble() {
        return cantidad.doubleValue();
    }


}


