package entidades;
// Generated 24 mar. 2022 12:52:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BalanceDifPesada generated by hbm2java
 */
public class BalanceDifPesada  implements java.io.Serializable {

     private Integer id;
     private Balance balance;
     private Cliente cliente= new Cliente();
     private Date fecha;
     private char turno;
     private BigDecimal valor;

    public BalanceDifPesada() {
    }

    public BalanceDifPesada(Balance balance, Cliente cliente, Date fecha, char turno, BigDecimal valor) {
       this.balance = balance;
       this.cliente = cliente;
       this.fecha = fecha;
       this.turno = turno;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balance getBalance() {
        return this.balance;
    }
    
    public void setBalance(Balance balance) {
        this.balance = balance;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public char getTurno() {
        return this.turno;
    }
    
    public void setTurno(char turno) {
        this.turno = turno;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


