package entidades;
// Generated 24 mar. 2022 12:52:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Balance generated by hbm2java
 */
public class Balance  implements java.io.Serializable {


     private Integer id;
     private LocalCarniceria localCarniceria;
     private int idUsuario;
     private Date fecCarga;
     private Date fecIni;
     private Date fecFin;
     private BigDecimal valorCobradoEfectivo;
     private BigDecimal valorCobrado;
     private BigDecimal valorRemanente;
     private BigDecimal valorGastos;
     private BigDecimal valorEfectivoCaja;
     private BigDecimal valorPorCobrar;
     private char estado;
     private Set<BalancePorCobrar> balancePorCobrars = new HashSet<BalancePorCobrar>(0);
     private Set<BalanceGastoPersonal> balanceGastoPersonals = new HashSet<BalanceGastoPersonal>(0);
     private Set<BalanceIngreso> balanceIngresos = new HashSet<BalanceIngreso>(0);
     private Set<BalanceGastoVario> balanceGastoVarios = new HashSet<BalanceGastoVario>(0);
     private Set<BalanceCobranza> balanceCobranzas = new HashSet<BalanceCobranza>(0);
     private Set<BalanceEfectivo> balanceEfectivos = new HashSet<BalanceEfectivo>(0);
     private Set<BalanceDifPesada> balanceDifPesadas = new HashSet<BalanceDifPesada>(0);
     private Set<BalanceGastoExtra> balanceGastoExtras = new HashSet<BalanceGastoExtra>(0);
     private Set<BalanceInvIni> balanceInvInis = new HashSet<BalanceInvIni>(0);
     private Set<BalanceRemanente> balanceRemanentes = new HashSet<BalanceRemanente>(0);

    public Balance() {
    }

	
    public Balance(LocalCarniceria localCarniceria, int idUsuario, Date fecCarga, Date fecIni, Date fecFin, BigDecimal valorCobradoEfectivo, BigDecimal valorCobrado, BigDecimal valorRemanente, BigDecimal valorGastos, BigDecimal valorEfectivoCaja, BigDecimal valorPorCobrar, char estado) {
        this.localCarniceria = localCarniceria;
        this.idUsuario = idUsuario;
        this.fecCarga = fecCarga;
        this.fecIni = fecIni;
        this.fecFin = fecFin;
        this.valorCobradoEfectivo = valorCobradoEfectivo;
        this.valorCobrado = valorCobrado;
        this.valorRemanente = valorRemanente;
        this.valorGastos = valorGastos;
        this.valorEfectivoCaja = valorEfectivoCaja;
        this.valorPorCobrar = valorPorCobrar;
        this.estado = estado;
    }
    public Balance(LocalCarniceria localCarniceria, int idUsuario, Date fecCarga, Date fecIni, Date fecFin, BigDecimal valorCobradoEfectivo, BigDecimal valorCobrado, BigDecimal valorRemanente, BigDecimal valorGastos, BigDecimal valorEfectivoCaja, BigDecimal valorPorCobrar, char estado, Set<BalancePorCobrar> balancePorCobrars, Set<BalanceGastoPersonal> balanceGastoPersonals, Set<BalanceIngreso> balanceIngresos, Set<BalanceGastoVario> balanceGastoVarios, Set<BalanceCobranza> balanceCobranzas, Set<BalanceEfectivo> balanceEfectivos, Set<BalanceDifPesada> balanceDifPesadas, Set<BalanceGastoExtra> balanceGastoExtras, Set<BalanceInvIni> balanceInvInis, Set<BalanceRemanente> balanceRemanentes) {
       this.localCarniceria = localCarniceria;
       this.idUsuario = idUsuario;
       this.fecCarga = fecCarga;
       this.fecIni = fecIni;
       this.fecFin = fecFin;
       this.valorCobradoEfectivo = valorCobradoEfectivo;
       this.valorCobrado = valorCobrado;
       this.valorRemanente = valorRemanente;
       this.valorGastos = valorGastos;
       this.valorEfectivoCaja = valorEfectivoCaja;
       this.valorPorCobrar = valorPorCobrar;
       this.estado = estado;
       this.balancePorCobrars = balancePorCobrars;
       this.balanceGastoPersonals = balanceGastoPersonals;
       this.balanceIngresos = balanceIngresos;
       this.balanceGastoVarios = balanceGastoVarios;
       this.balanceCobranzas = balanceCobranzas;
       this.balanceEfectivos = balanceEfectivos;
       this.balanceDifPesadas = balanceDifPesadas;
       this.balanceGastoExtras = balanceGastoExtras;
       this.balanceInvInis = balanceInvInis;
       this.balanceRemanentes = balanceRemanentes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecIni() {
        return this.fecIni;
    }
    
    public void setFecIni(Date fecIni) {
        this.fecIni = fecIni;
    }
    public Date getFecFin() {
        return this.fecFin;
    }
    
    public void setFecFin(Date fecFin) {
        this.fecFin = fecFin;
    }
    public BigDecimal getValorCobradoEfectivo() {
        return this.valorCobradoEfectivo;
    }
    
    public void setValorCobradoEfectivo(BigDecimal valorCobradoEfectivo) {
        this.valorCobradoEfectivo = valorCobradoEfectivo;
    }
    public BigDecimal getValorCobrado() {
        return this.valorCobrado;
    }
    
    public void setValorCobrado(BigDecimal valorCobrado) {
        this.valorCobrado = valorCobrado;
    }
    public BigDecimal getValorRemanente() {
        return this.valorRemanente;
    }
    
    public void setValorRemanente(BigDecimal valorRemanente) {
        this.valorRemanente = valorRemanente;
    }
    public BigDecimal getValorGastos() {
        return this.valorGastos;
    }
    
    public void setValorGastos(BigDecimal valorGastos) {
        this.valorGastos = valorGastos;
    }
    public BigDecimal getValorEfectivoCaja() {
        return this.valorEfectivoCaja;
    }
    
    public void setValorEfectivoCaja(BigDecimal valorEfectivoCaja) {
        this.valorEfectivoCaja = valorEfectivoCaja;
    }
    public BigDecimal getValorPorCobrar() {
        return this.valorPorCobrar;
    }
    
    public void setValorPorCobrar(BigDecimal valorPorCobrar) {
        this.valorPorCobrar = valorPorCobrar;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<BalancePorCobrar> getBalancePorCobrars() {
        return this.balancePorCobrars;
    }
    
    public void setBalancePorCobrars(Set<BalancePorCobrar> balancePorCobrars) {
        this.balancePorCobrars = balancePorCobrars;
    }
    public Set<BalanceGastoPersonal> getBalanceGastoPersonals() {
        return this.balanceGastoPersonals;
    }
    
    public void setBalanceGastoPersonals(Set<BalanceGastoPersonal> balanceGastoPersonals) {
        this.balanceGastoPersonals = balanceGastoPersonals;
    }
    public Set<BalanceIngreso> getBalanceIngresos() {
        return this.balanceIngresos;
    }
    
    public void setBalanceIngresos(Set<BalanceIngreso> balanceIngresos) {
        this.balanceIngresos = balanceIngresos;
    }
    public Set<BalanceGastoVario> getBalanceGastoVarios() {
        return this.balanceGastoVarios;
    }
    
    public void setBalanceGastoVarios(Set<BalanceGastoVario> balanceGastoVarios) {
        this.balanceGastoVarios = balanceGastoVarios;
    }
    public Set<BalanceCobranza> getBalanceCobranzas() {
        return this.balanceCobranzas;
    }
    
    public void setBalanceCobranzas(Set<BalanceCobranza> balanceCobranzas) {
        this.balanceCobranzas = balanceCobranzas;
    }
    public Set<BalanceEfectivo> getBalanceEfectivos() {
        return this.balanceEfectivos;
    }
    
    public void setBalanceEfectivos(Set<BalanceEfectivo> balanceEfectivos) {
        this.balanceEfectivos = balanceEfectivos;
    }
    public Set<BalanceDifPesada> getBalanceDifPesadas() {
        return this.balanceDifPesadas;
    }
    
    public void setBalanceDifPesadas(Set<BalanceDifPesada> balanceDifPesadas) {
        this.balanceDifPesadas = balanceDifPesadas;
    }
    public Set<BalanceGastoExtra> getBalanceGastoExtras() {
        return this.balanceGastoExtras;
    }
    
    public void setBalanceGastoExtras(Set<BalanceGastoExtra> balanceGastoExtras) {
        this.balanceGastoExtras = balanceGastoExtras;
    }
    public Set<BalanceInvIni> getBalanceInvInis() {
        return this.balanceInvInis;
    }
    
    public void setBalanceInvInis(Set<BalanceInvIni> balanceInvInis) {
        this.balanceInvInis = balanceInvInis;
    }
    public Set<BalanceRemanente> getBalanceRemanentes() {
        return this.balanceRemanentes;
    }
    
    public void setBalanceRemanentes(Set<BalanceRemanente> balanceRemanentes) {
        this.balanceRemanentes = balanceRemanentes;
    }




}


