package entidades;
// Generated 3 ene. 2022 16:12:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BalancePorCobrar generated by hbm2java
 */
public class BalancePorCobrar  implements java.io.Serializable {


     private Integer id;
     private Balance balance;
     private Cliente cliente= new Cliente();
     private Date fecha;
     private BigDecimal valor;
     private String observaciones;

    public BalancePorCobrar() {
    }

	
    public BalancePorCobrar(Balance balance, Cliente cliente, BigDecimal valor) {
        this.balance = balance;
        this.cliente = cliente;
        this.valor = valor;
    }
    public BalancePorCobrar(Balance balance, Cliente cliente, BigDecimal valor, String observaciones) {
       this.balance = balance;
       this.cliente = cliente;
       this.valor = valor;
       this.observaciones = observaciones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balance getBalance() {
        return this.balance;
    }
    
    public void setBalance(Balance balance) {
        this.balance = balance;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


