package entidades;
// Generated 15 ene. 2022 13:01:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BalanceCobranza generated by hbm2java
 */
public class BalanceCobranza  implements java.io.Serializable {


     private Integer id;
     private Balance balance;
     private Date fecha;
     private char turno;
     private int idFormaPago;
     private Integer idTarjeta;
     private BigDecimal valor;
     private String observaciones;

    public BalanceCobranza() {
    }

	
    public BalanceCobranza(Balance balance, Date fecha, char turno, int idFormaPago, BigDecimal valor) {
        this.balance = balance;
        this.fecha = fecha;
        this.turno = turno;
        this.idFormaPago = idFormaPago;
        this.valor = valor;
    }
    public BalanceCobranza(Balance balance, Date fecha, char turno, int idFormaPago, Integer idTarjeta, BigDecimal valor) {
       this.balance = balance;
       this.fecha = fecha;
       this.turno = turno;
       this.idFormaPago = idFormaPago;
       this.idTarjeta = idTarjeta;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balance getBalance() {
        return this.balance;
    }
    
    public void setBalance(Balance balance) {
        this.balance = balance;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public char getTurno() {
        return this.turno;
    }
    
    public void setTurno(char turno) {
        this.turno = turno;
    }
    public int getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(int idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public Integer getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(Integer idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


