package entidades;
// Generated 26 ene. 2022 14:40:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Short id;
     private String nombre;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Cargo() {
    }

	
    public Cargo(String nombre) {
        this.nombre = nombre;
    }
    public Cargo(String nombre, Set<Empleado> empleados) {
       this.nombre = nombre;
       this.empleados = empleados;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


