package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private Producto producto= new Producto();
     private String nombre;
     private Set<TropaDet> tropaDets = new HashSet<TropaDet>(0);
     private Set<Tropa> tropas = new HashSet<Tropa>(0);
     private Set<TropaDetGarron> tropaDetGarrons = new HashSet<TropaDetGarron>(0);
     private Set<CategoriaDet> categoriaDets = new HashSet<CategoriaDet>(0);

    public Categoria() {
    }

	
    public Categoria(Producto producto, String nombre) {
        this.producto = producto;
        this.nombre = nombre;
    }
    public Categoria(Producto producto, String nombre, Set<TropaDet> tropaDets, Set<Tropa> tropas, Set<TropaDetGarron> tropaDetGarrons, Set<CategoriaDet> categoriaDets) {
       this.producto = producto;
       this.nombre = nombre;
       this.tropaDets = tropaDets;
       this.tropas = tropas;
       this.tropaDetGarrons = tropaDetGarrons;
       this.categoriaDets = categoriaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<TropaDet> getTropaDets() {
        return this.tropaDets;
    }
    
    public void setTropaDets(Set<TropaDet> tropaDets) {
        this.tropaDets = tropaDets;
    }
    public Set<Tropa> getTropas() {
        return this.tropas;
    }
    
    public void setTropas(Set<Tropa> tropas) {
        this.tropas = tropas;
    }
    public Set<TropaDetGarron> getTropaDetGarrons() {
        return this.tropaDetGarrons;
    }
    
    public void setTropaDetGarrons(Set<TropaDetGarron> tropaDetGarrons) {
        this.tropaDetGarrons = tropaDetGarrons;
    }
    public Set<CategoriaDet> getCategoriaDets() {
        return this.categoriaDets;
    }
    
    public void setCategoriaDets(Set<CategoriaDet> categoriaDets) {
        this.categoriaDets = categoriaDets;
    }




}


