package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1



/**
 * CategoriaDet generated by hbm2java
 */
public class CategoriaDet  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria= new Categoria();
     private Producto producto= new Producto();
     private String tipo;

    public CategoriaDet() {
    }

    public CategoriaDet(Categoria categoria, Producto producto, String tipo) {
       this.categoria = categoria;
       this.producto = producto;
       this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


