package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Chofer generated by hbm2java
 */
public class Chofer  implements java.io.Serializable {


     private Short id;
     private Tipoid tipoid= new Tipoid();
     private String numId;
     private String nombre;
     private char estado;
     private Integer idUsuario;
     private char tipo;
     private String ccCostoTropa;
     private Set<EfectivoFlete> efectivoFletes = new HashSet<EfectivoFlete>(0);
     private Set<Viaje> viajes = new HashSet<Viaje>(0);
     private Set<LiquidacionFlete> liquidacionFletes = new HashSet<LiquidacionFlete>(0);

    public Chofer() {
    }

	
    public Chofer(String nombre, char estado, char tipo) {
        this.nombre = nombre;
        this.estado = estado;
        this.tipo = tipo;
    }
    public Chofer(Tipoid tipoid, String numId, String nombre, char estado, Integer idUsuario, char tipo, Set<EfectivoFlete> efectivoFletes, Set<Viaje> viajes, Set<LiquidacionFlete> liquidacionFletes) {
       this.tipoid = tipoid;
       this.numId = numId;
       this.nombre = nombre;
       this.estado = estado;
       this.idUsuario = idUsuario;
       this.tipo = tipo;
       this.efectivoFletes = efectivoFletes;
       this.viajes = viajes;
       this.liquidacionFletes = liquidacionFletes;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public Tipoid getTipoid() {
        return this.tipoid;
    }
    
    public void setTipoid(Tipoid tipoid) {
        this.tipoid = tipoid;
    }
    public String getNumId() {
        return this.numId;
    }
    
    public void setNumId(String numId) {
        this.numId = numId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }

    public String getCcCostoTropa() {
        return ccCostoTropa;
    }

    public void setCcCostoTropa(String ccCostoTropa) {
        this.ccCostoTropa = ccCostoTropa;
    }
    
    
    public Set<EfectivoFlete> getEfectivoFletes() {
        return this.efectivoFletes;
    }
    
    public void setEfectivoFletes(Set<EfectivoFlete> efectivoFletes) {
        this.efectivoFletes = efectivoFletes;
    }
    public Set<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set<Viaje> viajes) {
        this.viajes = viajes;
    }
    public Set<LiquidacionFlete> getLiquidacionFletes() {
        return this.liquidacionFletes;
    }
    
    public void setLiquidacionFletes(Set<LiquidacionFlete> liquidacionFletes) {
        this.liquidacionFletes = liquidacionFletes;
    }




}


