package entidades;
// Generated 24 mar. 2022 12:52:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private CondIva condIva;
     private Localidad localidad;
     private Provincia provincia;
     private Tipoid tipoid;
     private String numId;
     private String nombre;
     private String direccion;
     private String telefono;
     private String email;
     private BigDecimal costoxTon;
     private BigDecimal porcIvaFlete;
     private char estado;
     private Set<CostoFleteAnimales> costoFleteAnimaleses = new HashSet<CostoFleteAnimales>(0);
     private Set<BalanceDifPesada> balanceDifPesadas = new HashSet<BalanceDifPesada>(0);
     private Set<RemitoVenta> remitoVentas = new HashSet<RemitoVenta>(0);
     private Set<BalancePorCobrar> balancePorCobrars = new HashSet<BalancePorCobrar>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);
     private Set<LocalCarniceria> localCarnicerias = new HashSet<LocalCarniceria>(0);
     private Set<Viaje> viajes = new HashSet<Viaje>(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, char estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Cliente(CondIva condIva, Localidad localidad, Provincia provincia, Tipoid tipoid, String numId, String nombre, String direccion, String telefono, String email, BigDecimal costoxTon, BigDecimal porcIvaFlete, char estado, Set<CostoFleteAnimales> costoFleteAnimaleses, Set<BalanceDifPesada> balanceDifPesadas, Set<RemitoVenta> remitoVentas, Set<BalancePorCobrar> balancePorCobrars, Set<Venta> ventas, Set<LocalCarniceria> localCarnicerias, Set<Viaje> viajes) {
       this.condIva = condIva;
       this.localidad = localidad;
       this.provincia = provincia;
       this.tipoid = tipoid;
       this.numId = numId;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.costoxTon = costoxTon;
       this.porcIvaFlete = porcIvaFlete;
       this.estado = estado;
       this.costoFleteAnimaleses = costoFleteAnimaleses;
       this.balanceDifPesadas = balanceDifPesadas;
       this.remitoVentas = remitoVentas;
       this.balancePorCobrars = balancePorCobrars;
       this.ventas = ventas;
       this.localCarnicerias = localCarnicerias;
       this.viajes = viajes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CondIva getCondIva() {
        return this.condIva;
    }
    
    public void setCondIva(CondIva condIva) {
        this.condIva = condIva;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public Tipoid getTipoid() {
        return this.tipoid;
    }
    
    public void setTipoid(Tipoid tipoid) {
        this.tipoid = tipoid;
    }
    public String getNumId() {
        return this.numId;
    }
    
    public void setNumId(String numId) {
        this.numId = numId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public BigDecimal getCostoxTon() {
        return this.costoxTon;
    }
    
    public void setCostoxTon(BigDecimal costoxTon) {
        this.costoxTon = costoxTon;
    }
    public BigDecimal getPorcIvaFlete() {
        return this.porcIvaFlete;
    }
    
    public void setPorcIvaFlete(BigDecimal porcIvaFlete) {
        this.porcIvaFlete = porcIvaFlete;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<CostoFleteAnimales> getCostoFleteAnimaleses() {
        return this.costoFleteAnimaleses;
    }
    
    public void setCostoFleteAnimaleses(Set<CostoFleteAnimales> costoFleteAnimaleses) {
        this.costoFleteAnimaleses = costoFleteAnimaleses;
    }
    public Set<BalanceDifPesada> getBalanceDifPesadas() {
        return this.balanceDifPesadas;
    }
    
    public void setBalanceDifPesadas(Set<BalanceDifPesada> balanceDifPesadas) {
        this.balanceDifPesadas = balanceDifPesadas;
    }
    public Set<RemitoVenta> getRemitoVentas() {
        return this.remitoVentas;
    }
    
    public void setRemitoVentas(Set<RemitoVenta> remitoVentas) {
        this.remitoVentas = remitoVentas;
    }
    public Set<BalancePorCobrar> getBalancePorCobrars() {
        return this.balancePorCobrars;
    }
    
    public void setBalancePorCobrars(Set<BalancePorCobrar> balancePorCobrars) {
        this.balancePorCobrars = balancePorCobrars;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }
    public Set<LocalCarniceria> getLocalCarnicerias() {
        return this.localCarnicerias;
    }
    
    public void setLocalCarnicerias(Set<LocalCarniceria> localCarnicerias) {
        this.localCarnicerias = localCarnicerias;
    }
    public Set<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set<Viaje> viajes) {
        this.viajes = viajes;
    }




}


