package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer id;
     private int idProveedor;
     private Date fecCarga;
     private Date fecMov;
     private String tipoCompro;
     private String numFact;
     private String tipoFact;
     private BigDecimal totalSinIva;
     private BigDecimal valorIva;
     private BigDecimal total;
     private Set<CompraDet> compraDets = new HashSet<CompraDet>(0);

    public Compra() {
    }

	
    public Compra(int idProveedor, Date fecCarga, Date fecMov, BigDecimal totalSinIva, BigDecimal valorIva, BigDecimal total) {
        this.idProveedor = idProveedor;
        this.fecCarga = fecCarga;
        this.fecMov = fecMov;
        this.totalSinIva = totalSinIva;
        this.valorIva = valorIva;
        this.total = total;
    }
    public Compra(int idProveedor, Date fecCarga, Date fecMov, String tipoCompro, String numFact, String tipoFact, BigDecimal totalSinIva, BigDecimal valorIva, BigDecimal total, Set<CompraDet> compraDets) {
       this.idProveedor = idProveedor;
       this.fecCarga = fecCarga;
       this.fecMov = fecMov;
       this.tipoCompro = tipoCompro;
       this.numFact = numFact;
       this.tipoFact = tipoFact;
       this.totalSinIva = totalSinIva;
       this.valorIva = valorIva;
       this.total = total;
       this.compraDets = compraDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public String getTipoCompro() {
        return this.tipoCompro;
    }
    
    public void setTipoCompro(String tipoCompro) {
        this.tipoCompro = tipoCompro;
    }
    public String getNumFact() {
        return this.numFact;
    }
    
    public void setNumFact(String numFact) {
        this.numFact = numFact;
    }
    public String getTipoFact() {
        return this.tipoFact;
    }
    
    public void setTipoFact(String tipoFact) {
        this.tipoFact = tipoFact;
    }
    public BigDecimal getTotalSinIva() {
        return this.totalSinIva;
    }
    
    public void setTotalSinIva(BigDecimal totalSinIva) {
        this.totalSinIva = totalSinIva;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Set<CompraDet> getCompraDets() {
        return this.compraDets;
    }
    
    public void setCompraDets(Set<CompraDet> compraDets) {
        this.compraDets = compraDets;
    }




}


