package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CompraDet generated by hbm2java
 */
public class CompraDet  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Producto producto;
     private BigDecimal precio;
     private BigDecimal cantidad;
     private BigDecimal valor;

    public CompraDet() {
    }

    public CompraDet(Compra compra, Producto producto, BigDecimal precio, BigDecimal cantidad, BigDecimal valor) {
       this.compra = compra;
       this.producto = producto;
       this.precio = precio;
       this.cantidad = cantidad;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


