package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CondIva generated by hbm2java
 */
public class CondIva  implements java.io.Serializable {


     private Short id;
     private String nombre;
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Productor> productors = new HashSet<Productor>(0);
     private Set<Comisionista> comisionistas = new HashSet<Comisionista>(0);

    public CondIva() {
    }

	
    public CondIva(String nombre) {
        this.nombre = nombre;
    }
    public CondIva(String nombre, Set<Proveedor> proveedors, Set<Cliente> clientes, Set<Persona> personas, Set<Productor> productors, Set<Comisionista> comisionistas) {
       this.nombre = nombre;
       this.proveedors = proveedors;
       this.clientes = clientes;
       this.personas = personas;
       this.productors = productors;
       this.comisionistas = comisionistas;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<Productor> getProductors() {
        return this.productors;
    }
    
    public void setProductors(Set<Productor> productors) {
        this.productors = productors;
    }
    public Set<Comisionista> getComisionistas() {
        return this.comisionistas;
    }
    
    public void setComisionistas(Set<Comisionista> comisionistas) {
        this.comisionistas = comisionistas;
    }




}


