package entidades;
// Generated 01/09/2020 16:20:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CostoFleteGranos generated by hbm2java
 */
public class CostoFleteGranos  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private TipoGrano tipoGrano;
     private BigDecimal costoxTon;
     private BigDecimal porcIva;

    public CostoFleteGranos() {
    }

    public CostoFleteGranos(Cliente cliente, TipoGrano tipoGrano, BigDecimal costoxTon, BigDecimal porcIva) {
       this.cliente = cliente;
       this.tipoGrano = tipoGrano;
       this.costoxTon = costoxTon;
       this.porcIva = porcIva;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public TipoGrano getTipoGrano() {
        return this.tipoGrano;
    }
    
    public void setTipoGrano(TipoGrano tipoGrano) {
        this.tipoGrano = tipoGrano;
    }
    public BigDecimal getCostoxTon() {
        return this.costoxTon;
    }
    
    public void setCostoxTon(BigDecimal costoxTon) {
        this.costoxTon = costoxTon;
    }
    public BigDecimal getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(BigDecimal porcIva) {
        this.porcIva = porcIva;
    }




}


