package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CostoFleteAnimales generated by hbm2java
 */
public class CostoFleteAnimales  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente= new Cliente();
     private char tipoJaula;
     private BigDecimal costoxKm;
     private BigDecimal kmArranque;
     private BigDecimal costoArranque;
     private BigDecimal costoSeguro;

    public CostoFleteAnimales() {
    }

    public CostoFleteAnimales(Cliente cliente, char tipoJaula, BigDecimal costoxKm, BigDecimal kmArranque, BigDecimal costoArranque, BigDecimal costoSeguro) {
       this.cliente = cliente;
       this.tipoJaula = tipoJaula;
       this.costoxKm = costoxKm;
       this.kmArranque = kmArranque;
       this.costoArranque = costoArranque;
       this.costoSeguro = costoSeguro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public char getTipoJaula() {
        return this.tipoJaula;
    }
    
    public void setTipoJaula(char tipoJaula) {
        this.tipoJaula = tipoJaula;
    }
    public BigDecimal getCostoxKm() {
        return this.costoxKm;
    }
    
    public void setCostoxKm(BigDecimal costoxKm) {
        this.costoxKm = costoxKm;
    }
    public BigDecimal getKmArranque() {
        return this.kmArranque;
    }
    
    public void setKmArranque(BigDecimal kmArranque) {
        this.kmArranque = kmArranque;
    }
    public BigDecimal getCostoArranque() {
        return this.costoArranque;
    }
    
    public void setCostoArranque(BigDecimal costoArranque) {
        this.costoArranque = costoArranque;
    }
    public BigDecimal getCostoSeguro() {
        return this.costoSeguro;
    }
    
    public void setCostoSeguro(BigDecimal costoSeguro) {
        this.costoSeguro = costoSeguro;
    }




}


