package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Deposito generated by hbm2java
 */
public class Deposito  implements java.io.Serializable {


     private Integer id;
     private Localidad localidad= new Localidad();
     private Provincia provincia= new Provincia();
     private char tipo;
     private String cuit;
     private String nombre;
     private String direccion;
     private String telefono;
     private String email;
     private char tipoCobroFaena;
     private BigDecimal precioUnidad;
     private String ccCostoTropa;
     private Set<Tropa> tropas = new HashSet<Tropa>(0);

    public Deposito() {
    }

	
    public Deposito(Localidad localidad, Provincia provincia, char tipo, String nombre, String direccion, char tipoCobroFaena, BigDecimal precioUnidad) {
        this.localidad = localidad;
        this.provincia = provincia;
        this.tipo = tipo;
        this.nombre = nombre;
        this.direccion = direccion;
        this.tipoCobroFaena = tipoCobroFaena;
        this.precioUnidad = precioUnidad;
    }
    public Deposito(Localidad localidad, Provincia provincia, char tipo, String cuit, String nombre, String direccion, String telefono, String email, char tipoCobroFaena, BigDecimal precioUnidad, Set<Tropa> tropas) {
       this.localidad = localidad;
       this.provincia = provincia;
       this.tipo = tipo;
       this.cuit = cuit;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.tipoCobroFaena = tipoCobroFaena;
       this.precioUnidad = precioUnidad;
       this.tropas = tropas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getTipoCobroFaena() {
        return this.tipoCobroFaena;
    }
    
    public void setTipoCobroFaena(char tipoCobroFaena) {
        this.tipoCobroFaena = tipoCobroFaena;
    }
    public BigDecimal getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(BigDecimal precioUnidad) {
        this.precioUnidad = precioUnidad;
    }

    public String getCcCostoTropa() {
        return ccCostoTropa;
    }

    public void setCcCostoTropa(String ccCostoTropa) {
        this.ccCostoTropa = ccCostoTropa;
    }
    
    
    public Set<Tropa> getTropas() {
        return this.tropas;
    }
    
    public void setTropas(Set<Tropa> tropas) {
        this.tropas = tropas;
    }




}


