package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EfectivoFlete generated by hbm2java
 */
public class EfectivoFlete  implements java.io.Serializable {


     private Integer id;
     private Chofer chofer= new Chofer();
     private int idUsuario;
     private Date fecha;
     private BigDecimal valor;
     private char procesado;
     private Set<LiquidacionEfectivo> liquidacionEfectivos = new HashSet<LiquidacionEfectivo>(0);

    public EfectivoFlete() {
    }

	
    public EfectivoFlete(Chofer chofer, int idUsuario, Date fecha, BigDecimal valor, char procesado) {
        this.chofer = chofer;
        this.idUsuario = idUsuario;
        this.fecha = fecha;
        this.valor = valor;
        this.procesado = procesado;
    }
    public EfectivoFlete(Chofer chofer, int idUsuario, Date fecha, BigDecimal valor, char procesado, Set<LiquidacionEfectivo> liquidacionEfectivos) {
       this.chofer = chofer;
       this.idUsuario = idUsuario;
       this.fecha = fecha;
       this.valor = valor;
       this.procesado = procesado;
       this.liquidacionEfectivos = liquidacionEfectivos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public char getProcesado() {
        return this.procesado;
    }
    
    public void setProcesado(char procesado) {
        this.procesado = procesado;
    }
    public Set<LiquidacionEfectivo> getLiquidacionEfectivos() {
        return this.liquidacionEfectivos;
    }
    
    public void setLiquidacionEfectivos(Set<LiquidacionEfectivo> liquidacionEfectivos) {
        this.liquidacionEfectivos = liquidacionEfectivos;
    }




}


