package entidades;
// Generated 26 ene. 2022 14:40:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {
     private Integer id;
     private Cargo cargo= new Cargo();
     private Localidad localidad= new Localidad();
     private Provincia provincia= new Provincia();
     private Pais pais= new Pais();
     private String apellido;
     private String nombre;
     private int legajo;
     private String numId;
     private Date fecNac;
     private String direccion;
     private String telefono;
     private String email;
     private Date fecIng;
     private Date fecAlta;
     private Date fecBaja;
     private char estado;
     private Set<LocalEmpleado> localEmpleados = new HashSet<LocalEmpleado>(0);
     private Set<BalanceGastoPersonal> balanceGastoPersonals = new HashSet<BalanceGastoPersonal>(0);

    public Empleado() {
    }

	
    public Empleado(Cargo cargo, Localidad localidad, Provincia provincia,Pais pais, String apellido, String nombre, char estado) {
        this.cargo = cargo;
        this.localidad = localidad;
        this.provincia = provincia;
        this.pais=pais;
        this.apellido = apellido;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Empleado(Cargo cargo, Localidad localidad, Provincia provincia, String apellido, String nombre, String numId, Date fecNac, String direccion, String telefono, Date fecIng, Date fecAlta, Date fecBaja, char estado, Set<LocalEmpleado> localEmpleados, Set<BalanceGastoPersonal> balanceGastoPersonals) {
       this.cargo = cargo;
       this.localidad = localidad;
       this.provincia = provincia;
       this.apellido = apellido;
       this.nombre = nombre;
       this.numId = numId;
       this.fecNac = fecNac;
       this.direccion = direccion;
       this.telefono = telefono;
       this.fecIng = fecIng;
       this.fecAlta = fecAlta;
       this.fecBaja = fecBaja;
       this.estado = estado;
       this.localEmpleados = localEmpleados;
       this.balanceGastoPersonals = balanceGastoPersonals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    public Pais getPais() {
        return pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }
    
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getLegajo() {
        return legajo;
    }

    public void setLegajo(int legajo) {
        this.legajo = legajo;
    }
    
    public String getNumId() {
        return this.numId;
    }
    
    public void setNumId(String numId) {
        this.numId = numId;
    }
    public Date getFecNac() {
        return this.fecNac;
    }
    
    public void setFecNac(Date fecNac) {
        this.fecNac = fecNac;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    public Date getFecIng() {
        return this.fecIng;
    }
    
    public void setFecIng(Date fecIng) {
        this.fecIng = fecIng;
    }
    public Date getFecAlta() {
        return this.fecAlta;
    }
    
    public void setFecAlta(Date fecAlta) {
        this.fecAlta = fecAlta;
    }
    public Date getFecBaja() {
        return this.fecBaja;
    }
    
    public void setFecBaja(Date fecBaja) {
        this.fecBaja = fecBaja;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<LocalEmpleado> getLocalEmpleados() {
        return this.localEmpleados;
    }
    
    public void setLocalEmpleados(Set<LocalEmpleado> localEmpleados) {
        this.localEmpleados = localEmpleados;
    }
    public Set<BalanceGastoPersonal> getBalanceGastoPersonals() {
        return this.balanceGastoPersonals;
    }
    
    public void setBalanceGastoPersonals(Set<BalanceGastoPersonal> balanceGastoPersonals) {
        this.balanceGastoPersonals = balanceGastoPersonals;
    }




}


