package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private Pais pais;
     private Provincia provincia;
     private String nombreFantasia;
     private String razonSocial;
     private String observaciones;
     private String cuit;
     private String direccion;
     private String telefonoFijo;
     private String telefonoMovil;
     private String contacto;
     private String email;
     private char estado;
     private String sitioWeb;
     private String sitioNoticias;
     private String textoPromociones;
     private char validarEmail;
     private byte[] logo;
     private String mpPublicKey;
     private String mpAccessToken;
     private BigDecimal porcViajesSimples;
     private BigDecimal porcViajesDobles;
     private BigDecimal pagoCuentaIva;
     private BigDecimal porcIngBrutos;
     private BigDecimal costoFleteEntrega;
     private BigDecimal porcIvaVentas;
     private String emailSistemas;
     private String claveEmail;
     private String hostSmtp;
     private Short puertoEmail;
     private String startTls;
     private String auth;
     private String ccCostoTropa;
     private String ccIngBrutos;
     private String ccPagoVep;
     private String ccVentaCarne;
     private String ccCostoMercVendida;
     private String ccTropasCamara;
     
     
    public Empresa() {
    }

	
    public Empresa(Pais pais, Provincia provincia, String nombreFantasia, char estado, char validarEmail, BigDecimal porcViajesSimples, BigDecimal porcViajesDobles, BigDecimal pagoCuentaIva, BigDecimal porcIngBrutos, BigDecimal costoFleteEntrega) {
        this.pais = pais;
        this.provincia = provincia;
        this.nombreFantasia = nombreFantasia;
        this.estado = estado;
        this.validarEmail = validarEmail;
        this.porcViajesSimples = porcViajesSimples;
        this.porcViajesDobles = porcViajesDobles;
        this.pagoCuentaIva = pagoCuentaIva;
        this.porcIngBrutos = porcIngBrutos;
        this.costoFleteEntrega = costoFleteEntrega;
    }
    public Empresa(Pais pais, Provincia provincia, String nombreFantasia, String razonSocial, String observaciones, String cuit, String direccion, String telefonoFijo, String telefonoMovil, String contacto, String email, char estado, String sitioWeb, String sitioNoticias, String textoPromociones, char validarEmail, byte[] logo, String mpPublicKey, String mpAccessToken, BigDecimal porcViajesSimples, BigDecimal porcViajesDobles, BigDecimal pagoCuentaIva, BigDecimal porcIngBrutos, BigDecimal costoFleteEntrega, String emailSistemas, String claveEmail, String hostSmtp, Short puertoEmail, String startTls, String auth) {
       this.pais = pais;
       this.provincia = provincia;
       this.nombreFantasia = nombreFantasia;
       this.razonSocial = razonSocial;
       this.observaciones = observaciones;
       this.cuit = cuit;
       this.direccion = direccion;
       this.telefonoFijo = telefonoFijo;
       this.telefonoMovil = telefonoMovil;
       this.contacto = contacto;
       this.email = email;
       this.estado = estado;
       this.sitioWeb = sitioWeb;
       this.sitioNoticias = sitioNoticias;
       this.textoPromociones = textoPromociones;
       this.validarEmail = validarEmail;
       this.logo = logo;
       this.mpPublicKey = mpPublicKey;
       this.mpAccessToken = mpAccessToken;
       this.porcViajesSimples = porcViajesSimples;
       this.porcViajesDobles = porcViajesDobles;
       this.pagoCuentaIva = pagoCuentaIva;
       this.porcIngBrutos = porcIngBrutos;
       this.costoFleteEntrega = costoFleteEntrega;
       this.emailSistemas = emailSistemas;
       this.claveEmail = claveEmail;
       this.hostSmtp = hostSmtp;
       this.puertoEmail = puertoEmail;
       this.startTls = startTls;
       this.auth = auth;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombreFantasia() {
        return this.nombreFantasia;
    }
    
    public void setNombreFantasia(String nombreFantasia) {
        this.nombreFantasia = nombreFantasia;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public String getSitioWeb() {
        return this.sitioWeb;
    }
    
    public void setSitioWeb(String sitioWeb) {
        this.sitioWeb = sitioWeb;
    }
    public String getSitioNoticias() {
        return this.sitioNoticias;
    }
    
    public void setSitioNoticias(String sitioNoticias) {
        this.sitioNoticias = sitioNoticias;
    }
    public String getTextoPromociones() {
        return this.textoPromociones;
    }
    
    public void setTextoPromociones(String textoPromociones) {
        this.textoPromociones = textoPromociones;
    }
    public char getValidarEmail() {
        return this.validarEmail;
    }
    
    public void setValidarEmail(char validarEmail) {
        this.validarEmail = validarEmail;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public String getMpPublicKey() {
        return this.mpPublicKey;
    }
    
    public void setMpPublicKey(String mpPublicKey) {
        this.mpPublicKey = mpPublicKey;
    }
    public String getMpAccessToken() {
        return this.mpAccessToken;
    }
    
    public void setMpAccessToken(String mpAccessToken) {
        this.mpAccessToken = mpAccessToken;
    }
    public BigDecimal getPorcViajesSimples() {
        return this.porcViajesSimples;
    }
    
    public void setPorcViajesSimples(BigDecimal porcViajesSimples) {
        this.porcViajesSimples = porcViajesSimples;
    }
    public BigDecimal getPorcViajesDobles() {
        return this.porcViajesDobles;
    }
    
    public void setPorcViajesDobles(BigDecimal porcViajesDobles) {
        this.porcViajesDobles = porcViajesDobles;
    }
    public BigDecimal getPagoCuentaIva() {
        return this.pagoCuentaIva;
    }
    
    public void setPagoCuentaIva(BigDecimal pagoCuentaIva) {
        this.pagoCuentaIva = pagoCuentaIva;
    }
    public BigDecimal getPorcIngBrutos() {
        return this.porcIngBrutos;
    }
    
    public void setPorcIngBrutos(BigDecimal porcIngBrutos) {
        this.porcIngBrutos = porcIngBrutos;
    }
    public BigDecimal getCostoFleteEntrega() {
        return this.costoFleteEntrega;
    }
    
    public void setCostoFleteEntrega(BigDecimal costoFleteEntrega) {
        this.costoFleteEntrega = costoFleteEntrega;
    }

    public BigDecimal getPorcIvaVentas() {
        return porcIvaVentas;
    }

    public void setPorcIvaVentas(BigDecimal porcIvaVentas) {
        this.porcIvaVentas = porcIvaVentas;
    }
    
    public String getEmailSistemas() {
        return this.emailSistemas;
    }
    
    public void setEmailSistemas(String emailSistemas) {
        this.emailSistemas = emailSistemas;
    }
    public String getClaveEmail() {
        return this.claveEmail;
    }
    
    public void setClaveEmail(String claveEmail) {
        this.claveEmail = claveEmail;
    }
    public String getHostSmtp() {
        return this.hostSmtp;
    }
    
    public void setHostSmtp(String hostSmtp) {
        this.hostSmtp = hostSmtp;
    }
    public Short getPuertoEmail() {
        return this.puertoEmail;
    }
    
    public void setPuertoEmail(Short puertoEmail) {
        this.puertoEmail = puertoEmail;
    }
    public String getStartTls() {
        return this.startTls;
    }
    
    public void setStartTls(String startTls) {
        this.startTls = startTls;
    }
    public String getAuth() {
        return this.auth;
    }
    
    public void setAuth(String auth) {
        this.auth = auth;
    }

    public String getCcCostoTropa() {
        return ccCostoTropa;
    }

    public void setCcCostoTropa(String ccCostoTropa) {
        this.ccCostoTropa = ccCostoTropa;
    }

    public String getCcIngBrutos() {
        return ccIngBrutos;
    }

    public void setCcIngBrutos(String ccIngBrutos) {
        this.ccIngBrutos = ccIngBrutos;
    }

    public String getCcPagoVep() {
        return ccPagoVep;
    }

    public void setCcPagoVep(String ccPagoVep) {
        this.ccPagoVep = ccPagoVep;
    }

    public String getCcVentaCarne() {
        return ccVentaCarne;
    }

    public void setCcVentaCarne(String ccVentaCarne) {
        this.ccVentaCarne = ccVentaCarne;
    }

    public String getCcCostoMercVendida() {
        return ccCostoMercVendida;
    }

    public void setCcCostoMercVendida(String ccCostoMercVendida) {
        this.ccCostoMercVendida = ccCostoMercVendida;
    }

    public String getCcTropasCamara() {
        return ccTropasCamara;
    }

    public void setCcTropasCamara(String ccTropasCamara) {
        this.ccTropasCamara = ccTropasCamara;
    }




}


