package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EntregaDet generated by hbm2java
 */
public class EntregaDet  implements java.io.Serializable {


     private Integer id;
     private Entrega entrega;
     private InventarioTropa inventarioTropa;
     private String tipo;
     public BigDecimal kilos;

    public EntregaDet() {
    }

    public EntregaDet(Entrega entrega, InventarioTropa inventarioTropa, String tipo, BigDecimal kilos) {
       this.entrega = entrega;
       this.inventarioTropa = inventarioTropa;
       this.tipo = tipo;
       this.kilos = kilos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Entrega getEntrega() {
        return this.entrega;
    }
    
    public void setEntrega(Entrega entrega) {
        this.entrega = entrega;
    }
    public InventarioTropa getInventarioTropa() {
        return this.inventarioTropa;
    }
    
    public void setInventarioTropa(InventarioTropa inventarioTropa) {
        this.inventarioTropa = inventarioTropa;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getKilos() {
        return this.kilos;
    }
    
    public void setKilos(BigDecimal kilos) {
        this.kilos = kilos;
    }

    public double getKilosDouble(){
        return kilos.doubleValue();
    }


}


