package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entrega generated by hbm2java
 */
public class Entrega  implements java.io.Serializable {


     private Integer id;
     private LocalCarniceria localCarniceria;
     private Date fecCarga;
     private int idUsuarioEntrega;
     private Date fecEnt;
     private Integer idUsuarioRecibe;
     private Date fecRec;
     private char estado;
     private BigDecimal totalKilos;
     private BigDecimal valorFlete;
     private String observaciones;
     private Set<EntregaDet> entregaDets = new HashSet<EntregaDet>(0);

    public Entrega() {
    }

	
    public Entrega(LocalCarniceria localCarniceria, Date fecCarga, int idUsuarioEntrega, Date fecEnt, char estado, BigDecimal totalKilos, BigDecimal valorFlete) {
        this.localCarniceria = localCarniceria;
        this.fecCarga = fecCarga;
        this.idUsuarioEntrega = idUsuarioEntrega;
        this.fecEnt = fecEnt;
        this.estado = estado;
        this.totalKilos = totalKilos;
        this.valorFlete = valorFlete;
    }
    public Entrega(LocalCarniceria localCarniceria, Date fecCarga, int idUsuarioEntrega, Date fecEnt, Integer idUsuarioRecibe, Date fecRec, char estado, BigDecimal totalKilos, BigDecimal valorFlete, String observaciones, Set<EntregaDet> entregaDets) {
       this.localCarniceria = localCarniceria;
       this.fecCarga = fecCarga;
       this.idUsuarioEntrega = idUsuarioEntrega;
       this.fecEnt = fecEnt;
       this.idUsuarioRecibe = idUsuarioRecibe;
       this.fecRec = fecRec;
       this.estado = estado;
       this.totalKilos = totalKilos;
       this.valorFlete = valorFlete;
       this.observaciones = observaciones;
       this.entregaDets = entregaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public int getIdUsuarioEntrega() {
        return this.idUsuarioEntrega;
    }
    
    public void setIdUsuarioEntrega(int idUsuarioEntrega) {
        this.idUsuarioEntrega = idUsuarioEntrega;
    }
    public Date getFecEnt() {
        return this.fecEnt;
    }
    
    public void setFecEnt(Date fecEnt) {
        this.fecEnt = fecEnt;
    }
    public Integer getIdUsuarioRecibe() {
        return this.idUsuarioRecibe;
    }
    
    public void setIdUsuarioRecibe(Integer idUsuarioRecibe) {
        this.idUsuarioRecibe = idUsuarioRecibe;
    }
    public Date getFecRec() {
        return this.fecRec;
    }
    
    public void setFecRec(Date fecRec) {
        this.fecRec = fecRec;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public BigDecimal getTotalKilos() {
        return this.totalKilos;
    }
    
    public void setTotalKilos(BigDecimal totalKilos) {
        this.totalKilos = totalKilos;
    }
    public BigDecimal getValorFlete() {
        return this.valorFlete;
    }
    
    public void setValorFlete(BigDecimal valorFlete) {
        this.valorFlete = valorFlete;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<EntregaDet> getEntregaDets() {
        return this.entregaDets;
    }
    
    public void setEntregaDets(Set<EntregaDet> entregaDets) {
        this.entregaDets = entregaDets;
    }

    @Override
    public String toString() {
        return "Entrega: " + id + " Local: " + localCarniceria.getNombreComercial() ;
    }




}


