package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<VentaCc> ventaCcs = new HashSet<VentaCc>(0);

    public FormaPago() {
    }

	
    public FormaPago(String nombre) {
        this.nombre = nombre;
    }
    public FormaPago(String nombre, Set<VentaCc> ventaCcs) {
       this.nombre = nombre;
       this.ventaCcs = ventaCcs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<VentaCc> getVentaCcs() {
        return this.ventaCcs;
    }
    
    public void setVentaCcs(Set<VentaCc> ventaCcs) {
        this.ventaCcs = ventaCcs;
    }




}


