package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gasto generated by hbm2java
 */
public class Gasto  implements java.io.Serializable {


     private Integer id;
     private TipoGasto tipoGasto= new TipoGasto();
     private Unidad unidad= new Unidad();
     private int idUsuario;
     private Date fecMov;
     private Date fecCarga;
     private BigDecimal cantidad;
     private BigDecimal valorGravado;
     private BigDecimal porcIva;
     private BigDecimal valorIva;
     private BigDecimal valorNoGravado;
     private BigDecimal valorTotal;
     private String observaciones;
     private char procesado;
     private Set<LiquidacionGasto> liquidacionGastos = new HashSet<LiquidacionGasto>(0);

    public Gasto() {
    }

	
    public Gasto(TipoGasto tipoGasto, Unidad unidad, int idUsuario, Date fecMov, Date fecCarga, BigDecimal cantidad, BigDecimal valorGravado, BigDecimal porcIva, BigDecimal valorIva, BigDecimal valorNoGravado, BigDecimal valorTotal, char procesado) {
        this.tipoGasto = tipoGasto;
        this.unidad = unidad;
        this.idUsuario = idUsuario;
        this.fecMov = fecMov;
        this.fecCarga = fecCarga;
        this.cantidad = cantidad;
        this.valorGravado = valorGravado;
        this.porcIva = porcIva;
        this.valorIva = valorIva;
        this.valorNoGravado = valorNoGravado;
        this.valorTotal = valorTotal;
        this.procesado = procesado;
    }
    public Gasto(TipoGasto tipoGasto, Unidad unidad, int idUsuario, Date fecMov, Date fecCarga, BigDecimal cantidad, BigDecimal valorGravado, BigDecimal porcIva, BigDecimal valorIva, BigDecimal valorNoGravado, BigDecimal valorTotal, String observaciones, char procesado, Set<LiquidacionGasto> liquidacionGastos) {
       this.tipoGasto = tipoGasto;
       this.unidad = unidad;
       this.idUsuario = idUsuario;
       this.fecMov = fecMov;
       this.fecCarga = fecCarga;
       this.cantidad = cantidad;
       this.valorGravado = valorGravado;
       this.porcIva = porcIva;
       this.valorIva = valorIva;
       this.valorNoGravado = valorNoGravado;
       this.valorTotal = valorTotal;
       this.observaciones = observaciones;
       this.procesado = procesado;
       this.liquidacionGastos = liquidacionGastos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoGasto getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(TipoGasto tipoGasto) {
        this.tipoGasto = tipoGasto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getValorGravado() {
        return this.valorGravado;
    }
    
    public void setValorGravado(BigDecimal valorGravado) {
        this.valorGravado = valorGravado;
    }
    public BigDecimal getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(BigDecimal porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }
    public BigDecimal getValorNoGravado() {
        return this.valorNoGravado;
    }
    
    public void setValorNoGravado(BigDecimal valorNoGravado) {
        this.valorNoGravado = valorNoGravado;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public char getProcesado() {
        return this.procesado;
    }
    
    public void setProcesado(char procesado) {
        this.procesado = procesado;
    }
    public Set<LiquidacionGasto> getLiquidacionGastos() {
        return this.liquidacionGastos;
    }
    
    public void setLiquidacionGastos(Set<LiquidacionGasto> liquidacionGastos) {
        this.liquidacionGastos = liquidacionGastos;
    }




}


