package entidades;
// Generated 16 jun. 2022 20:10:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * InventarioTropa generated by hbm2java
 */
public class InventarioTropa  implements java.io.Serializable {


     private Integer id;
     private Tropa tropa;
     private TropaDetGarron tropaDetGarron;
     private String tipo;
     private BigDecimal kilos;
     private char estado;
     private Set<RemitoVentaDet> remitoVentaDets = new HashSet<RemitoVentaDet>(0);
     private Set<EntregaDet> entregaDets = new HashSet<EntregaDet>(0);

    public InventarioTropa() {
    }

	
    public InventarioTropa(Tropa tropa, TropaDetGarron tropaDetGarron, String tipo, BigDecimal kilos, char estado) {
        this.tropa = tropa;
        this.tropaDetGarron = tropaDetGarron;
        this.tipo = tipo;
        this.kilos = kilos;
        this.estado = estado;
    }
    public InventarioTropa(Tropa tropa, TropaDetGarron tropaDetGarron, String tipo, BigDecimal kilos, char estado, Set<RemitoVentaDet> remitoVentaDets, Set<EntregaDet> entregaDets) {
       this.tropa = tropa;
       this.tropaDetGarron = tropaDetGarron;
       this.tipo = tipo;
       this.kilos = kilos;
       this.estado = estado;
       this.remitoVentaDets = remitoVentaDets;
       this.entregaDets = entregaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tropa getTropa() {
        return this.tropa;
    }
    
    public void setTropa(Tropa tropa) {
        this.tropa = tropa;
    }
    public TropaDetGarron getTropaDetGarron() {
        return this.tropaDetGarron;
    }
    
    public void setTropaDetGarron(TropaDetGarron tropaDetGarron) {
        this.tropaDetGarron = tropaDetGarron;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getKilos() {
        return this.kilos;
    }
    
    public void setKilos(BigDecimal kilos) {
        this.kilos = kilos;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<RemitoVentaDet> getRemitoVentaDets() {
        return this.remitoVentaDets;
    }
    
    public void setRemitoVentaDets(Set<RemitoVentaDet> remitoVentaDets) {
        this.remitoVentaDets = remitoVentaDets;
    }
    public Set<EntregaDet> getEntregaDets() {
        return this.entregaDets;
    }
    
    public void setEntregaDets(Set<EntregaDet> entregaDets) {
        this.entregaDets = entregaDets;
    }




}


