package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LiquidacionFlete generated by hbm2java
 */
public class LiquidacionFlete  implements java.io.Serializable {


     private Integer id;
     private Chofer chofer= new Chofer();
     private int idUsuario;
     private Date fecMov;
     private Date fecCarga;
     private Integer kilometrosActuales;
     private Integer kilometrosAnteriores;
     private Integer kilometrosRecorridos;
     private String observaciones;
     private BigDecimal totalViajesSimples;
     private BigDecimal porcViajesSimples;
     private BigDecimal valorViajesSimples;
     private BigDecimal totalViajesDobles;
     private BigDecimal porcViajesDobles;
     private BigDecimal valorViajesDobles;
     private BigDecimal totalViajes;
     private BigDecimal valorViajes;
     private BigDecimal valorEfectivos;
     private BigDecimal valorGastos;
     private BigDecimal vueltoCaja;
     private BigDecimal cargasSociales;
     private BigDecimal totalPagar;
     private char procesada;
     private Set<LiquidacionViaje> liquidacionViajes = new HashSet<LiquidacionViaje>(0);
     private Set<LiquidacionGasto> liquidacionGastos = new HashSet<LiquidacionGasto>(0);
     private Set<LiquidacionEfectivo> liquidacionEfectivos = new HashSet<LiquidacionEfectivo>(0);

    public LiquidacionFlete() {
    }

	
    public LiquidacionFlete(Chofer chofer, int idUsuario, Date fecMov, Date fecCarga, char procesada) {
        this.chofer = chofer;
        this.idUsuario = idUsuario;
        this.fecMov = fecMov;
        this.fecCarga = fecCarga;
        this.procesada = procesada;
    }
    public LiquidacionFlete(Chofer chofer, int idUsuario, Date fecMov, Date fecCarga, Integer kilometrosActuales, Integer kilometrosAnteriores, Integer kilometrosRecorridos, String observaciones, BigDecimal totalViajesSimples, BigDecimal porcViajesSimples, BigDecimal valorViajesSimples, BigDecimal totalViajesDobles, BigDecimal porcViajesDobles, BigDecimal valorViajesDobles, BigDecimal totalViajes, BigDecimal valorViajes, BigDecimal valorEfectivos, BigDecimal valorGastos, BigDecimal vueltoCaja, BigDecimal cargasSociales, BigDecimal totalPagar, char procesada, Set<LiquidacionViaje> liquidacionViajes, Set<LiquidacionGasto> liquidacionGastos, Set<LiquidacionEfectivo> liquidacionEfectivos) {
       this.chofer = chofer;
       this.idUsuario = idUsuario;
       this.fecMov = fecMov;
       this.fecCarga = fecCarga;
       this.kilometrosActuales = kilometrosActuales;
       this.kilometrosAnteriores = kilometrosAnteriores;
       this.kilometrosRecorridos = kilometrosRecorridos;
       this.observaciones = observaciones;
       this.totalViajesSimples = totalViajesSimples;
       this.porcViajesSimples = porcViajesSimples;
       this.valorViajesSimples = valorViajesSimples;
       this.totalViajesDobles = totalViajesDobles;
       this.porcViajesDobles = porcViajesDobles;
       this.valorViajesDobles = valorViajesDobles;
       this.totalViajes = totalViajes;
       this.valorViajes = valorViajes;
       this.valorEfectivos = valorEfectivos;
       this.valorGastos = valorGastos;
       this.vueltoCaja = vueltoCaja;
       this.cargasSociales = cargasSociales;
       this.totalPagar = totalPagar;
       this.procesada = procesada;
       this.liquidacionViajes = liquidacionViajes;
       this.liquidacionGastos = liquidacionGastos;
       this.liquidacionEfectivos = liquidacionEfectivos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Integer getKilometrosActuales() {
        return this.kilometrosActuales;
    }
    
    public void setKilometrosActuales(Integer kilometrosActuales) {
        this.kilometrosActuales = kilometrosActuales;
    }
    public Integer getKilometrosAnteriores() {
        return this.kilometrosAnteriores;
    }
    
    public void setKilometrosAnteriores(Integer kilometrosAnteriores) {
        this.kilometrosAnteriores = kilometrosAnteriores;
    }
    public Integer getKilometrosRecorridos() {
        return this.kilometrosRecorridos;
    }
    
    public void setKilometrosRecorridos(Integer kilometrosRecorridos) {
        this.kilometrosRecorridos = kilometrosRecorridos;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public BigDecimal getTotalViajesSimples() {
        return this.totalViajesSimples;
    }
    
    public void setTotalViajesSimples(BigDecimal totalViajesSimples) {
        this.totalViajesSimples = totalViajesSimples;
    }
    public BigDecimal getPorcViajesSimples() {
        return this.porcViajesSimples;
    }
    
    public void setPorcViajesSimples(BigDecimal porcViajesSimples) {
        this.porcViajesSimples = porcViajesSimples;
    }
    public BigDecimal getValorViajesSimples() {
        return this.valorViajesSimples;
    }
    
    public void setValorViajesSimples(BigDecimal valorViajesSimples) {
        this.valorViajesSimples = valorViajesSimples;
    }
    public BigDecimal getTotalViajesDobles() {
        return this.totalViajesDobles;
    }
    
    public void setTotalViajesDobles(BigDecimal totalViajesDobles) {
        this.totalViajesDobles = totalViajesDobles;
    }
    public BigDecimal getPorcViajesDobles() {
        return this.porcViajesDobles;
    }
    
    public void setPorcViajesDobles(BigDecimal porcViajesDobles) {
        this.porcViajesDobles = porcViajesDobles;
    }
    public BigDecimal getValorViajesDobles() {
        return this.valorViajesDobles;
    }
    
    public void setValorViajesDobles(BigDecimal valorViajesDobles) {
        this.valorViajesDobles = valorViajesDobles;
    }
    public BigDecimal getTotalViajes() {
        return this.totalViajes;
    }
    
    public void setTotalViajes(BigDecimal totalViajes) {
        this.totalViajes = totalViajes;
    }
    public BigDecimal getValorViajes() {
        return this.valorViajes;
    }
    
    public void setValorViajes(BigDecimal valorViajes) {
        this.valorViajes = valorViajes;
    }
    public BigDecimal getValorEfectivos() {
        return this.valorEfectivos;
    }
    
    public void setValorEfectivos(BigDecimal valorEfectivos) {
        this.valorEfectivos = valorEfectivos;
    }
    public BigDecimal getValorGastos() {
        return this.valorGastos;
    }
    
    public void setValorGastos(BigDecimal valorGastos) {
        this.valorGastos = valorGastos;
    }
    public BigDecimal getVueltoCaja() {
        return this.vueltoCaja;
    }
    
    public void setVueltoCaja(BigDecimal vueltoCaja) {
        this.vueltoCaja = vueltoCaja;
    }
    public BigDecimal getCargasSociales() {
        return this.cargasSociales;
    }
    
    public void setCargasSociales(BigDecimal cargasSociales) {
        this.cargasSociales = cargasSociales;
    }
    public BigDecimal getTotalPagar() {
        return this.totalPagar;
    }
    
    public void setTotalPagar(BigDecimal totalPagar) {
        this.totalPagar = totalPagar;
    }
    public char getProcesada() {
        return this.procesada;
    }
    
    public void setProcesada(char procesada) {
        this.procesada = procesada;
    }
    public Set<LiquidacionViaje> getLiquidacionViajes() {
        return this.liquidacionViajes;
    }
    
    public void setLiquidacionViajes(Set<LiquidacionViaje> liquidacionViajes) {
        this.liquidacionViajes = liquidacionViajes;
    }
    public Set<LiquidacionGasto> getLiquidacionGastos() {
        return this.liquidacionGastos;
    }
    
    public void setLiquidacionGastos(Set<LiquidacionGasto> liquidacionGastos) {
        this.liquidacionGastos = liquidacionGastos;
    }
    public Set<LiquidacionEfectivo> getLiquidacionEfectivos() {
        return this.liquidacionEfectivos;
    }
    
    public void setLiquidacionEfectivos(Set<LiquidacionEfectivo> liquidacionEfectivos) {
        this.liquidacionEfectivos = liquidacionEfectivos;
    }




}


