package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1



/**
 * LiquidacionGasto generated by hbm2java
 */
public class LiquidacionGasto  implements java.io.Serializable {


     private Integer id;
     private Gasto gasto;
     private LiquidacionFlete liquidacionFlete= new LiquidacionFlete();

    public LiquidacionGasto() {
    }

    public LiquidacionGasto(Gasto gasto, LiquidacionFlete liquidacionFlete) {
       this.gasto = gasto;
       this.liquidacionFlete = liquidacionFlete;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Gasto getGasto() {
        return this.gasto;
    }
    
    public void setGasto(Gasto gasto) {
        this.gasto = gasto;
    }
    public LiquidacionFlete getLiquidacionFlete() {
        return this.liquidacionFlete;
    }
    
    public void setLiquidacionFlete(LiquidacionFlete liquidacionFlete) {
        this.liquidacionFlete = liquidacionFlete;
    }




}


