package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1



/**
 * LiquidacionEfectivo generated by hbm2java
 */
public class LiquidacionEfectivo  implements java.io.Serializable {


     private Integer id;
     private EfectivoFlete efectivoFlete= new EfectivoFlete();
     private LiquidacionFlete liquidacionFlete= new LiquidacionFlete();

    public LiquidacionEfectivo() {
    }

    public LiquidacionEfectivo(EfectivoFlete efectivoFlete, LiquidacionFlete liquidacionFlete) {
       this.efectivoFlete = efectivoFlete;
       this.liquidacionFlete = liquidacionFlete;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EfectivoFlete getEfectivoFlete() {
        return this.efectivoFlete;
    }
    
    public void setEfectivoFlete(EfectivoFlete efectivoFlete) {
        this.efectivoFlete = efectivoFlete;
    }
    public LiquidacionFlete getLiquidacionFlete() {
        return this.liquidacionFlete;
    }
    
    public void setLiquidacionFlete(LiquidacionFlete liquidacionFlete) {
        this.liquidacionFlete = liquidacionFlete;
    }




}


