package entidades;
// Generated 4 abr. 2022 15:58:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ListaPrecios generated by hbm2java
 */
public class ListaPrecios  implements java.io.Serializable {
     private Integer id;
     private int idUsuario;
     private Date fecCarga;
     private Date fecIni;
     private Date fecFin;
     private String observaciones;
     private Set<ListaPreciosDet> listaPreciosDets = new HashSet<ListaPreciosDet>(0);

    public ListaPrecios() {
    }

	
    public ListaPrecios(int idUsuario, Date fecCarga, Date fecIni, Date fecFin) {
        this.idUsuario = idUsuario;
        this.fecCarga = fecCarga;
        this.fecIni = fecIni;
        this.fecFin = fecFin;
    }
    public ListaPrecios(int idUsuario, Date fecCarga, Date fecIni, Date fecFin, String observaciones, Set<ListaPreciosDet> listaPreciosDets) {
       this.idUsuario = idUsuario;
       this.fecCarga = fecCarga;
       this.fecIni = fecIni;
       this.fecFin = fecFin;
       this.observaciones = observaciones;
       this.listaPreciosDets = listaPreciosDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecIni() {
        return this.fecIni;
    }
    
    public void setFecIni(Date fecIni) {
        this.fecIni = fecIni;
    }
    public Date getFecFin() {
        return this.fecFin;
    }
    
    public void setFecFin(Date fecFin) {
        this.fecFin = fecFin;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<ListaPreciosDet> getListaPreciosDets() {
        return this.listaPreciosDets;
    }
    
    public void setListaPreciosDets(Set<ListaPreciosDet> listaPreciosDets) {
        this.listaPreciosDets = listaPreciosDets;
    }




}


