package entidades;
// Generated 4 abr. 2022 15:58:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ListaPreciosLocal generated by hbm2java
 */
public class ListaPreciosLocal  implements java.io.Serializable {


     private Integer id;
     private LocalCarniceria localCarniceria;
     private int idUsuario;
     private Date fecCarga;
     private Date fecIni;
     private Date fecFin;
     private String observaciones;
     private Set<ListaPreciosLocalDet> listaPreciosLocalDets = new HashSet<ListaPreciosLocalDet>(0);

    public ListaPreciosLocal() {
    }

	
    public ListaPreciosLocal(LocalCarniceria localCarniceria, int idUsuario, Date fecCarga, Date fecIni, Date fecFin) {
        this.localCarniceria = localCarniceria;
        this.idUsuario = idUsuario;
        this.fecCarga = fecCarga;
        this.fecIni = fecIni;
        this.fecFin = fecFin;
    }
    public ListaPreciosLocal(LocalCarniceria localCarniceria, int idUsuario, Date fecCarga, Date fecIni, Date fecFin, String observaciones, Set<ListaPreciosLocalDet> listaPreciosLocalDets) {
       this.localCarniceria = localCarniceria;
       this.idUsuario = idUsuario;
       this.fecCarga = fecCarga;
       this.fecIni = fecIni;
       this.fecFin = fecFin;
       this.observaciones = observaciones;
       this.listaPreciosLocalDets = listaPreciosLocalDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecIni() {
        return this.fecIni;
    }
    
    public void setFecIni(Date fecIni) {
        this.fecIni = fecIni;
    }
    public Date getFecFin() {
        return this.fecFin;
    }
    
    public void setFecFin(Date fecFin) {
        this.fecFin = fecFin;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<ListaPreciosLocalDet> getListaPreciosLocalDets() {
        return this.listaPreciosLocalDets;
    }
    
    public void setListaPreciosLocalDets(Set<ListaPreciosLocalDet> listaPreciosLocalDets) {
        this.listaPreciosLocalDets = listaPreciosLocalDets;
    }




}


