package entidades;
// Generated 15 jun. 2022 17:29:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LocalCarniceria generated by hbm2java
 */
public class LocalCarniceria  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente= new Cliente();
     private Localidad localidad= new Localidad();
     private Provincia provincia= new Provincia();
     private String nombreComercial;
     private Integer idUsuarioEncargado;
     private String responsable;
     private String direccion;
     private String telefono;
     private String email;
     private String horarioMa;
     private String horarioTa;
     private char estado;
     private Integer plantillaCobranzas;
     private String ccVentaLocal;
     private Set<RemitoVenta> remitoVentas = new HashSet<RemitoVenta>(0);
     private Set<LocalRubro> localRubros = new HashSet<LocalRubro>(0);
     private Set<ListaPreciosLocal> listaPreciosLocals = new HashSet<ListaPreciosLocal>(0);
     private Set<LocalEmpleado> localEmpleados = new HashSet<LocalEmpleado>(0);
     private Set<Balance> balances = new HashSet<Balance>(0);
     private Set<Entrega> entregas = new HashSet<Entrega>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public LocalCarniceria() {
    }

	
    public LocalCarniceria(Cliente cliente, Localidad localidad, Provincia provincia, String nombreComercial, String direccion, char estado) {
        this.cliente = cliente;
        this.localidad = localidad;
        this.provincia = provincia;
        this.nombreComercial = nombreComercial;
        this.direccion = direccion;
        this.estado = estado;
    }
    public LocalCarniceria(Cliente cliente, Localidad localidad, Provincia provincia, String nombreComercial, Integer idUsuarioEncargado, String responsable, String direccion, String telefono, String email, String horarioMa, String horarioTa, char estado, Integer plantillaCobranzas, String ccVentaLocal, Set<RemitoVenta> remitoVentas, Set<LocalRubro> localRubros, Set<ListaPreciosLocal> listaPreciosLocals, Set<LocalEmpleado> localEmpleados, Set<Balance> balances, Set<Entrega> entregas, Set<Venta> ventas) {
       this.cliente = cliente;
       this.localidad = localidad;
       this.provincia = provincia;
       this.nombreComercial = nombreComercial;
       this.idUsuarioEncargado = idUsuarioEncargado;
       this.responsable = responsable;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.horarioMa = horarioMa;
       this.horarioTa = horarioTa;
       this.estado = estado;
       this.plantillaCobranzas = plantillaCobranzas;
       this.ccVentaLocal = ccVentaLocal;
       this.remitoVentas = remitoVentas;
       this.localRubros = localRubros;
       this.listaPreciosLocals = listaPreciosLocals;
       this.localEmpleados = localEmpleados;
       this.balances = balances;
       this.entregas = entregas;
       this.ventas = ventas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public Integer getIdUsuarioEncargado() {
        return this.idUsuarioEncargado;
    }
    
    public void setIdUsuarioEncargado(Integer idUsuarioEncargado) {
        this.idUsuarioEncargado = idUsuarioEncargado;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getHorarioMa() {
        return this.horarioMa;
    }
    
    public void setHorarioMa(String horarioMa) {
        this.horarioMa = horarioMa;
    }
    public String getHorarioTa() {
        return this.horarioTa;
    }
    
    public void setHorarioTa(String horarioTa) {
        this.horarioTa = horarioTa;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Integer getPlantillaCobranzas() {
        return this.plantillaCobranzas;
    }
    
    public void setPlantillaCobranzas(Integer plantillaCobranzas) {
        this.plantillaCobranzas = plantillaCobranzas;
    }
    public String getCcVentaLocal() {
        return this.ccVentaLocal;
    }
    
    public void setCcVentaLocal(String ccVentaLocal) {
        this.ccVentaLocal = ccVentaLocal;
    }
    public Set<RemitoVenta> getRemitoVentas() {
        return this.remitoVentas;
    }
    
    public void setRemitoVentas(Set<RemitoVenta> remitoVentas) {
        this.remitoVentas = remitoVentas;
    }
    public Set<LocalRubro> getLocalRubros() {
        return this.localRubros;
    }
    
    public void setLocalRubros(Set<LocalRubro> localRubros) {
        this.localRubros = localRubros;
    }
    public Set<ListaPreciosLocal> getListaPreciosLocals() {
        return this.listaPreciosLocals;
    }
    
    public void setListaPreciosLocals(Set<ListaPreciosLocal> listaPreciosLocals) {
        this.listaPreciosLocals = listaPreciosLocals;
    }
    public Set<LocalEmpleado> getLocalEmpleados() {
        return this.localEmpleados;
    }
    
    public void setLocalEmpleados(Set<LocalEmpleado> localEmpleados) {
        this.localEmpleados = localEmpleados;
    }
    public Set<Balance> getBalances() {
        return this.balances;
    }
    
    public void setBalances(Set<Balance> balances) {
        this.balances = balances;
    }
    public Set<Entrega> getEntregas() {
        return this.entregas;
    }
    
    public void setEntregas(Set<Entrega> entregas) {
        this.entregas = entregas;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


