package entidades;
// Generated 21 ene. 2022 15:27:07 by Hibernate Tools 4.3.1



/**
 * LocalRubro generated by hbm2java
 */

public class LocalRubro  implements java.io.Serializable {

     private Integer id;
     private Rubro rubro;
     private LocalCarniceria localCarniceria;

    public LocalRubro() {
    }

    public LocalRubro(Rubro rubro, LocalCarniceria localCarniceria) {
       this.rubro = rubro;
       this.localCarniceria = localCarniceria;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }

}


