package entidades;
// Generated 26 ene. 2022 14:40:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private Integer id;
     private Provincia provincia;
     private String nombre;
     private Set<Repartidor> repartidors = new HashSet<Repartidor>(0);
     private Set<DireccionUsuarioCliente> direccionUsuarioClientes = new HashSet<DireccionUsuarioCliente>(0);
     private Set<LocalCarniceria> localCarnicerias = new HashSet<LocalCarniceria>(0);
     private Set<Deposito> depositos = new HashSet<Deposito>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Comisionista> comisionistas = new HashSet<Comisionista>(0);
     private Set<Productor> productors = new HashSet<Productor>(0);
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<Viaje> viajesForIdOrigen = new HashSet<Viaje>(0);
     private Set<Viaje> viajesForIdDestino = new HashSet<Viaje>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Localidad() {
    }

	
    public Localidad(Provincia provincia, String nombre) {
        this.provincia = provincia;
        this.nombre = nombre;
    }
    public Localidad(Provincia provincia, String nombre, Set<Repartidor> repartidors, Set<DireccionUsuarioCliente> direccionUsuarioClientes, Set<LocalCarniceria> localCarnicerias, Set<Deposito> depositos, Set<Cliente> clientes, Set<Comisionista> comisionistas, Set<Productor> productors, Set<Proveedor> proveedors, Set<Viaje> viajesForIdOrigen, Set<Viaje> viajesForIdDestino, Set<Empleado> empleados) {
       this.provincia = provincia;
       this.nombre = nombre;
       this.repartidors = repartidors;
       this.direccionUsuarioClientes = direccionUsuarioClientes;
       this.localCarnicerias = localCarnicerias;
       this.depositos = depositos;
       this.clientes = clientes;
       this.comisionistas = comisionistas;
       this.productors = productors;
       this.proveedors = proveedors;
       this.viajesForIdOrigen = viajesForIdOrigen;
       this.viajesForIdDestino = viajesForIdDestino;
       this.empleados = empleados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Repartidor> getRepartidors() {
        return this.repartidors;
    }
    
    public void setRepartidors(Set<Repartidor> repartidors) {
        this.repartidors = repartidors;
    }
    public Set<DireccionUsuarioCliente> getDireccionUsuarioClientes() {
        return this.direccionUsuarioClientes;
    }
    
    public void setDireccionUsuarioClientes(Set<DireccionUsuarioCliente> direccionUsuarioClientes) {
        this.direccionUsuarioClientes = direccionUsuarioClientes;
    }
    public Set<LocalCarniceria> getLocalCarnicerias() {
        return this.localCarnicerias;
    }
    
    public void setLocalCarnicerias(Set<LocalCarniceria> localCarnicerias) {
        this.localCarnicerias = localCarnicerias;
    }
    public Set<Deposito> getDepositos() {
        return this.depositos;
    }
    
    public void setDepositos(Set<Deposito> depositos) {
        this.depositos = depositos;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Comisionista> getComisionistas() {
        return this.comisionistas;
    }
    
    public void setComisionistas(Set<Comisionista> comisionistas) {
        this.comisionistas = comisionistas;
    }
    public Set<Productor> getProductors() {
        return this.productors;
    }
    
    public void setProductors(Set<Productor> productors) {
        this.productors = productors;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }
    public Set<Viaje> getViajesForIdOrigen() {
        return this.viajesForIdOrigen;
    }
    
    public void setViajesForIdOrigen(Set<Viaje> viajesForIdOrigen) {
        this.viajesForIdOrigen = viajesForIdOrigen;
    }
    public Set<Viaje> getViajesForIdDestino() {
        return this.viajesForIdDestino;
    }
    
    public void setViajesForIdDestino(Set<Viaje> viajesForIdDestino) {
        this.viajesForIdDestino = viajesForIdDestino;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


