package entidades;
// Generated 21 ene. 2022 15:27:07 by Hibernate Tools 4.3.1



/**
 * LocalEmpleado generated by hbm2java
 */
public class LocalEmpleado  implements java.io.Serializable {


     private Integer id;
     private Empleado empleado;
     private LocalCarniceria localCarniceria;

    public LocalEmpleado() {
    }

    public LocalEmpleado(Empleado empleado, LocalCarniceria localCarniceria) {
       this.empleado = empleado;
       this.localCarniceria = localCarniceria;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }




}


