package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Marca() {
    }

	
    public Marca(String nombre) {
        this.nombre = nombre;
    }
    public Marca(String nombre, Set<Producto> productos) {
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


