package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String simbolo;
     private Set<Pais> paises = new HashSet<Pais>(0);
     private Set<CuentaBanco> cuentaBancos = new HashSet<CuentaBanco>(0);

    public Moneda() {
    }

	
    public Moneda(String nombre, String simbolo) {
        this.nombre = nombre;
        this.simbolo = simbolo;
    }
    public Moneda(String nombre, String simbolo, Set<Pais> paises, Set<CuentaBanco> cuentaBancos) {
       this.nombre = nombre;
       this.simbolo = simbolo;
       this.paises = paises;
       this.cuentaBancos = cuentaBancos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSimbolo() {
        return this.simbolo;
    }
    
    public void setSimbolo(String simbolo) {
        this.simbolo = simbolo;
    }
    public Set<Pais> getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set<Pais> paises) {
        this.paises = paises;
    }
    public Set<CuentaBanco> getCuentaBancos() {
        return this.cuentaBancos;
    }
    
    public void setCuentaBancos(Set<CuentaBanco> cuentaBancos) {
        this.cuentaBancos = cuentaBancos;
    }




}


