package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MovStockDet generated by hbm2java
 */
public class MovStockDet  implements java.io.Serializable {


     private Integer id;
     private MovStock movStock;
     private Producto producto;
     private Unidad unidad;
     private BigDecimal cantidad;

    public MovStockDet() {
    }

    public MovStockDet(MovStock movStock, Producto producto, Unidad unidad, BigDecimal cantidad) {
       this.movStock = movStock;
       this.producto = producto;
       this.unidad = unidad;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MovStock getMovStock() {
        return this.movStock;
    }
    
    public void setMovStock(MovStock movStock) {
        this.movStock = movStock;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


