package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PorcentajeIva generated by hbm2java
 */
public class PorcentajeIva  implements java.io.Serializable {


     private Short id;
     private String nombre;
     private BigDecimal porcentaje;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public PorcentajeIva() {
    }

	
    public PorcentajeIva(String nombre, BigDecimal porcentaje) {
        this.nombre = nombre;
        this.porcentaje = porcentaje;
    }
    public PorcentajeIva(String nombre, BigDecimal porcentaje, Set<Producto> productos) {
       this.nombre = nombre;
       this.porcentaje = porcentaje;
       this.productos = productos;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


