package entidades;
// Generated 3 ene. 2022 16:12:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer id;
     private CondIva condIva= new CondIva();
     private Localidad localidad= new Localidad();
     private Provincia provincia= new Provincia();
     private Tipoid tipoid= new Tipoid();
     private String numId;
     private String nombre;
     private String direccion;
     private String telefono;
     private String email;
     private char estado;
     private Set<BalanceIngreso> balanceIngresos = new HashSet<BalanceIngreso>(0);
     private Set<BalanceGastoVario> balanceGastoVarios = new HashSet<BalanceGastoVario>(0);
     private Set<BalanceGastoExtra> balanceGastoExtras = new HashSet<BalanceGastoExtra>(0);
     private Set<BalanceGastoPersonal> balanceGastoPersonals = new HashSet<BalanceGastoPersonal>(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, char estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Proveedor(CondIva condIva, Localidad localidad, Provincia provincia, Tipoid tipoid, String numId, String nombre, String direccion, String telefono, String email, char estado, Set<BalanceIngreso> balanceIngresos, Set<BalanceGastoVario> balanceGastoVarios, Set<BalanceGastoExtra> balanceGastoExtras, Set<BalanceGastoPersonal> balanceGastoPersonals) {
       this.condIva = condIva;
       this.localidad = localidad;
       this.provincia = provincia;
       this.tipoid = tipoid;
       this.numId = numId;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.estado = estado;
       this.balanceIngresos = balanceIngresos;
       this.balanceGastoVarios = balanceGastoVarios;
       this.balanceGastoExtras = balanceGastoExtras;
       this.balanceGastoPersonals = balanceGastoPersonals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CondIva getCondIva() {
        return this.condIva;
    }
    
    public void setCondIva(CondIva condIva) {
        this.condIva = condIva;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public Tipoid getTipoid() {
        return this.tipoid;
    }
    
    public void setTipoid(Tipoid tipoid) {
        this.tipoid = tipoid;
    }
    public String getNumId() {
        return this.numId;
    }
    
    public void setNumId(String numId) {
        this.numId = numId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<BalanceIngreso> getBalanceIngresos() {
        return this.balanceIngresos;
    }
    
    public void setBalanceIngresos(Set<BalanceIngreso> balanceIngresos) {
        this.balanceIngresos = balanceIngresos;
    }
    public Set<BalanceGastoVario> getBalanceGastoVarios() {
        return this.balanceGastoVarios;
    }
    
    public void setBalanceGastoVarios(Set<BalanceGastoVario> balanceGastoVarios) {
        this.balanceGastoVarios = balanceGastoVarios;
    }
    public Set<BalanceGastoExtra> getBalanceGastoExtras() {
        return this.balanceGastoExtras;
    }
    
    public void setBalanceGastoExtras(Set<BalanceGastoExtra> balanceGastoExtras) {
        this.balanceGastoExtras = balanceGastoExtras;
    }
    public Set<BalanceGastoPersonal> getBalanceGastoPersonals() {
        return this.balanceGastoPersonals;
    }
    
    public void setBalanceGastoPersonals(Set<BalanceGastoPersonal> balanceGastoPersonals) {
        this.balanceGastoPersonals = balanceGastoPersonals;
    }




}


