package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RemitoVenta generated by hbm2java
 */
public class RemitoVenta  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private LocalCarniceria localCarniceria;
     private String tipoMov;
     private int idUsuario;
     private Date fecCarga;
     private Date fecMov;
     private String observaciones;
     private char estado;
     private Set<RemitoVentaDet> remitoVentaDets = new HashSet<RemitoVentaDet>(0);
     private Set<VentaEstanciaRemito> ventaEstanciaRemitos = new HashSet<VentaEstanciaRemito>(0);

    public RemitoVenta() {
    }

	
    public RemitoVenta(Cliente cliente, String tipoMov, int idUsuario, Date fecCarga, Date fecMov, char estado) {
        this.cliente = cliente;
        this.tipoMov = tipoMov;
        this.idUsuario = idUsuario;
        this.fecCarga = fecCarga;
        this.fecMov = fecMov;
        this.estado = estado;
    }
    public RemitoVenta(Cliente cliente, LocalCarniceria localCarniceria, String tipoMov, int idUsuario, Date fecCarga, Date fecMov, String observaciones, char estado, Set<RemitoVentaDet> remitoVentaDets, Set<VentaEstanciaRemito> ventaEstanciaRemitos) {
       this.cliente = cliente;
       this.localCarniceria = localCarniceria;
       this.tipoMov = tipoMov;
       this.idUsuario = idUsuario;
       this.fecCarga = fecCarga;
       this.fecMov = fecMov;
       this.observaciones = observaciones;
       this.estado = estado;
       this.remitoVentaDets = remitoVentaDets;
       this.ventaEstanciaRemitos = ventaEstanciaRemitos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<RemitoVentaDet> getRemitoVentaDets() {
        return this.remitoVentaDets;
    }
    
    public void setRemitoVentaDets(Set<RemitoVentaDet> remitoVentaDets) {
        this.remitoVentaDets = remitoVentaDets;
    }
    public Set<VentaEstanciaRemito> getVentaEstanciaRemitos() {
        return this.ventaEstanciaRemitos;
    }
    
    public void setVentaEstanciaRemitos(Set<VentaEstanciaRemito> ventaEstanciaRemitos) {
        this.ventaEstanciaRemitos = ventaEstanciaRemitos;
    }




}


