package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RemitoVentaDet generated by hbm2java
 */
public class RemitoVentaDet  implements java.io.Serializable {


     private Integer id;
     private InventarioTropa inventarioTropa;
     private Producto producto;
     private RemitoVenta remitoVenta;
     private Unidad unidad;
     private BigDecimal cantidad;

    public RemitoVentaDet() {
    }

	
    public RemitoVentaDet(Producto producto, RemitoVenta remitoVenta, Unidad unidad, BigDecimal cantidad) {
        this.producto = producto;
        this.remitoVenta = remitoVenta;
        this.unidad = unidad;
        this.cantidad = cantidad;
    }
    public RemitoVentaDet(InventarioTropa inventarioTropa, Producto producto, RemitoVenta remitoVenta, Unidad unidad, BigDecimal cantidad) {
       this.inventarioTropa = inventarioTropa;
       this.producto = producto;
       this.remitoVenta = remitoVenta;
       this.unidad = unidad;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public InventarioTropa getInventarioTropa() {
        return this.inventarioTropa;
    }
    
    public void setInventarioTropa(InventarioTropa inventarioTropa) {
        this.inventarioTropa = inventarioTropa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public RemitoVenta getRemitoVenta() {
        return this.remitoVenta;
    }
    
    public void setRemitoVenta(RemitoVenta remitoVenta) {
        this.remitoVenta = remitoVenta;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


