package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Repartidor generated by hbm2java
 */
public class Repartidor  implements java.io.Serializable {


     private Integer id;
     private Localidad localidad;
     private Provincia provincia;
     private Tipoid tipoid;
     private String numId;
     private String nombre;
     private String direccion;
     private String telefono;
     private String email;
     private Date fecNac;
     private char estado;

    public Repartidor() {
    }

	
    public Repartidor(String nombre, char estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Repartidor(Localidad localidad, Provincia provincia, Tipoid tipoid, String numId, String nombre, String direccion, String telefono, String email, Date fecNac, char estado) {
       this.localidad = localidad;
       this.provincia = provincia;
       this.tipoid = tipoid;
       this.numId = numId;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.fecNac = fecNac;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public Tipoid getTipoid() {
        return this.tipoid;
    }
    
    public void setTipoid(Tipoid tipoid) {
        this.tipoid = tipoid;
    }
    public String getNumId() {
        return this.numId;
    }
    
    public void setNumId(String numId) {
        this.numId = numId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFecNac() {
        return this.fecNac;
    }
    
    public void setFecNac(Date fecNac) {
        this.fecNac = fecNac;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


