package entidades;
// Generated 22 jun. 2023 20:30:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name="tarjeta"
    ,catalog="estancia"
)
public class Tarjeta  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<VentaCc> ventaCcs = new HashSet<VentaCc>(0);
     private Set<TarjetaPlan> tarjetaPlans = new HashSet<TarjetaPlan>(0);

    public Tarjeta() {
    }

	
    public Tarjeta(String nombre) {
        this.nombre = nombre;
    }
    public Tarjeta(String nombre, Set<VentaCc> ventaCcs, Set<TarjetaPlan> tarjetaPlans) {
       this.nombre = nombre;
       this.ventaCcs = ventaCcs;
       this.tarjetaPlans = tarjetaPlans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tarjeta")
    public Set<VentaCc> getVentaCcs() {
        return this.ventaCcs;
    }
    
    public void setVentaCcs(Set<VentaCc> ventaCcs) {
        this.ventaCcs = ventaCcs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tarjeta", cascade = CascadeType.ALL,orphanRemoval=true)
    public Set<TarjetaPlan> getTarjetaPlans() {
        return this.tarjetaPlans;
    }
    
    public void setTarjetaPlans(Set<TarjetaPlan> tarjetaPlans) {
        tarjetaPlans.forEach((t) -> {
            t.setTarjeta(this);
        });
        this.tarjetaPlans = tarjetaPlans;
    }




}


