package entidades;
// Generated 22 jun. 2023 20:30:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TarjetaPlan generated by hbm2java
 */
@Entity
@Table(name="tarjeta_plan"
    ,catalog="estancia"
)
public class TarjetaPlan  implements java.io.Serializable {


     private Integer id = 0;
     private Tarjeta tarjeta;
     private String nombre;
     private int cuotas = 0;
     private BigDecimal porcRecargo = new BigDecimal(BigInteger.ZERO);

    public TarjetaPlan() {
        
    }

    public TarjetaPlan(Tarjeta tarjeta, String nombre, int cuotas, BigDecimal porcRecargo) {
       this.tarjeta = tarjeta;
       this.nombre = nombre;
       this.cuotas = cuotas;
       this.porcRecargo = porcRecargo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTarjeta", nullable=false)
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="cuotas", nullable=false)
    public int getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(int cuotas) {
        this.cuotas = cuotas;
    }

    
    @Column(name="porc_recargo", nullable=false, precision=10)
    public BigDecimal getPorcRecargo() {
        return this.porcRecargo;
    }
    
    public void setPorcRecargo(BigDecimal porcRecargo) {
        this.porcRecargo = porcRecargo;
    }




}


