package entidades;
// Generated 3 ene. 2022 16:12:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoGasto generated by hbm2java
 */
public class TipoGasto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private BigDecimal alicuotaIva;
     private Set<Gasto> gastos = new HashSet<Gasto>(0);
     private Set<BalanceGastoVario> balanceGastoVarios = new HashSet<BalanceGastoVario>(0);
     private Set<UnidadNegocioGasto> unidadNegocioGastos = new HashSet<UnidadNegocioGasto>(0);
     private Set<BalanceGastoExtra> balanceGastoExtras = new HashSet<BalanceGastoExtra>(0);
     private Set<BalanceGastoPersonal> balanceGastoPersonals = new HashSet<BalanceGastoPersonal>(0);

    public TipoGasto() {
    }

	
    public TipoGasto(String nombre) {
        this.nombre = nombre;
    }
    public TipoGasto(String nombre, BigDecimal alicuotaIva, Set<Gasto> gastos, Set<BalanceGastoVario> balanceGastoVarios, Set<UnidadNegocioGasto> unidadNegocioGastos, Set<BalanceGastoExtra> balanceGastoExtras, Set<BalanceGastoPersonal> balanceGastoPersonals) {
       this.nombre = nombre;
       this.alicuotaIva = alicuotaIva;
       this.gastos = gastos;
       this.balanceGastoVarios = balanceGastoVarios;
       this.unidadNegocioGastos = unidadNegocioGastos;
       this.balanceGastoExtras = balanceGastoExtras;
       this.balanceGastoPersonals = balanceGastoPersonals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getAlicuotaIva() {
        return this.alicuotaIva;
    }
    
    public void setAlicuotaIva(BigDecimal alicuotaIva) {
        this.alicuotaIva = alicuotaIva;
    }
    public Set<Gasto> getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set<Gasto> gastos) {
        this.gastos = gastos;
    }
    public Set<BalanceGastoVario> getBalanceGastoVarios() {
        return this.balanceGastoVarios;
    }
    
    public void setBalanceGastoVarios(Set<BalanceGastoVario> balanceGastoVarios) {
        this.balanceGastoVarios = balanceGastoVarios;
    }
    public Set<UnidadNegocioGasto> getUnidadNegocioGastos() {
        return this.unidadNegocioGastos;
    }
    
    public void setUnidadNegocioGastos(Set<UnidadNegocioGasto> unidadNegocioGastos) {
        this.unidadNegocioGastos = unidadNegocioGastos;
    }
    public Set<BalanceGastoExtra> getBalanceGastoExtras() {
        return this.balanceGastoExtras;
    }
    
    public void setBalanceGastoExtras(Set<BalanceGastoExtra> balanceGastoExtras) {
        this.balanceGastoExtras = balanceGastoExtras;
    }
    public Set<BalanceGastoPersonal> getBalanceGastoPersonals() {
        return this.balanceGastoPersonals;
    }
    
    public void setBalanceGastoPersonals(Set<BalanceGastoPersonal> balanceGastoPersonals) {
        this.balanceGastoPersonals = balanceGastoPersonals;
    }




}


