package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoid generated by hbm2java
 */
public class Tipoid  implements java.io.Serializable {


     private Short id;
     private String nombre;
     private Set<Repartidor> repartidors = new HashSet<Repartidor>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Productor> productors = new HashSet<Productor>(0);
     private Set<Chofer> chofers = new HashSet<Chofer>(0);
     private Set<Comisionista> comisionistas = new HashSet<Comisionista>(0);

    public Tipoid() {
    }

	
    public Tipoid(String nombre) {
        this.nombre = nombre;
    }
    public Tipoid(String nombre, Set<Repartidor> repartidors, Set<Cliente> clientes, Set<Productor> productors, Set<Chofer> chofers, Set<Comisionista> comisionistas) {
       this.nombre = nombre;
       this.repartidors = repartidors;
       this.clientes = clientes;
       this.productors = productors;
       this.chofers = chofers;
       this.comisionistas = comisionistas;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Repartidor> getRepartidors() {
        return this.repartidors;
    }
    
    public void setRepartidors(Set<Repartidor> repartidors) {
        this.repartidors = repartidors;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Productor> getProductors() {
        return this.productors;
    }
    
    public void setProductors(Set<Productor> productors) {
        this.productors = productors;
    }
    public Set<Chofer> getChofers() {
        return this.chofers;
    }
    
    public void setChofers(Set<Chofer> chofers) {
        this.chofers = chofers;
    }
    public Set<Comisionista> getComisionistas() {
        return this.comisionistas;
    }
    
    public void setComisionistas(Set<Comisionista> comisionistas) {
        this.comisionistas = comisionistas;
    }




}


