package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TropaDet generated by hbm2java
 */
public class TropaDet  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria= new Categoria();
     private Tropa tropa= new Tropa();
     private int cabezasVivas;
     private int cabezasDte;
     private BigDecimal kilosVivosOriginal;
     private BigDecimal porcDesbaste;
     private BigDecimal kilosVivos;
     private BigDecimal kilosVivosReales;
     private int decomisos;
     private short mediasReces;
     private int cabezasFaenadas;
     private int cabezasMuertas;
     private BigDecimal kilosFaenados;
     private BigDecimal kilosDecomisados;
     private BigDecimal rendimiento;
     private BigDecimal porcIvaProductor;
     private BigDecimal precioKiloVivo;
     private BigDecimal importeKiloVivoSinIva;
     private BigDecimal entregaEfectivoB;
     private BigDecimal importeKiloVivoImponible;
     private BigDecimal ivaKiloVivo;
     private BigDecimal importeKiloVivo;
     private BigDecimal precioKiloFaenado;
     private BigDecimal importeFaena;
     private BigDecimal porcIngBrutos;
     private BigDecimal valorIngBrutos;
     private BigDecimal pagoCuentaIva;
     private BigDecimal porcComision;
     private BigDecimal porcIvaComisionista;
     private BigDecimal importeComisionSinIva;
     private BigDecimal entregaEfectivoComisionB;
     private BigDecimal importeComisionImponible;
     private BigDecimal ivaComision;
     private BigDecimal importeComision;
     private BigDecimal importeCostoTotalSinIva;
     private BigDecimal importeCostoTotal;
     private String observaciones;

    public TropaDet() {
    }

    public TropaDet(int cabezasVivas, int cabezasDte, BigDecimal kilosVivosOriginal, BigDecimal porcDesbaste, BigDecimal kilosVivos, BigDecimal kilosVivosReales, int decomisos, short mediasReces, int cabezasFaenadas, int cabezasMuertas, BigDecimal kilosFaenados, BigDecimal kilosDecomisados, BigDecimal rendimiento, BigDecimal porcIvaProductor, BigDecimal precioKiloVivo, BigDecimal importeKiloVivoSinIva, BigDecimal entregaEfectivoB, BigDecimal importeKiloVivoImponible, BigDecimal ivaKiloVivo, BigDecimal importeKiloVivo, BigDecimal precioKiloFaenado, BigDecimal importeFaena, BigDecimal porcIngBrutos, BigDecimal valorIngBrutos, BigDecimal pagoCuentaIva, BigDecimal porcComision, BigDecimal porcIvaComisionista, BigDecimal importeComisionSinIva, BigDecimal entregaEfectivoComisionB, BigDecimal importeComisionImponible, BigDecimal ivaComision, BigDecimal importeComision, BigDecimal importeCostoTotalSinIva, BigDecimal importeCostoTotal, String observaciones) {
        this.cabezasVivas = cabezasVivas;
        this.cabezasDte = cabezasDte;
        this.kilosVivosOriginal = kilosVivosOriginal;
        this.porcDesbaste = porcDesbaste;
        this.kilosVivos = kilosVivos;
        this.kilosVivosReales = kilosVivosReales;
        this.decomisos = decomisos;
        this.mediasReces = mediasReces;
        this.cabezasFaenadas = cabezasFaenadas;
        this.cabezasMuertas = cabezasMuertas;
        this.kilosFaenados = kilosFaenados;
        this.kilosDecomisados = kilosDecomisados;
        this.rendimiento = rendimiento;
        this.porcIvaProductor = porcIvaProductor;
        this.precioKiloVivo = precioKiloVivo;
        this.importeKiloVivoSinIva = importeKiloVivoSinIva;
        this.entregaEfectivoB = entregaEfectivoB;
        this.importeKiloVivoImponible = importeKiloVivoImponible;
        this.ivaKiloVivo = ivaKiloVivo;
        this.importeKiloVivo = importeKiloVivo;
        this.precioKiloFaenado = precioKiloFaenado;
        this.importeFaena = importeFaena;
        this.porcIngBrutos = porcIngBrutos;
        this.valorIngBrutos = valorIngBrutos;
        this.pagoCuentaIva = pagoCuentaIva;
        this.porcComision = porcComision;
        this.porcIvaComisionista = porcIvaComisionista;
        this.importeComisionSinIva = importeComisionSinIva;
        this.entregaEfectivoComisionB = entregaEfectivoComisionB;
        this.importeComisionImponible = importeComisionImponible;
        this.ivaComision = ivaComision;
        this.importeComision = importeComision;
        this.importeCostoTotalSinIva = importeCostoTotalSinIva;
        this.importeCostoTotal = importeCostoTotal;
        this.observaciones = observaciones;
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Tropa getTropa() {
        return this.tropa;
    }
    
    public void setTropa(Tropa tropa) {
        this.tropa = tropa;
    }
    public int getCabezasVivas() {
        return this.cabezasVivas;
    }
    
    public void setCabezasVivas(int cabezasVivas) {
        this.cabezasVivas = cabezasVivas;
    }
    public int getCabezasDte() {
        return this.cabezasDte;
    }
    
    public void setCabezasDte(int cabezasDte) {
        this.cabezasDte = cabezasDte;
    }
    public BigDecimal getKilosVivos() {
        return this.kilosVivos;
    }
    
    public void setKilosVivos(BigDecimal kilosVivos) {
        this.kilosVivos = kilosVivos;
    }

    public BigDecimal getKilosVivosOriginal() {
        return kilosVivosOriginal;
    }

    public void setKilosVivosOriginal(BigDecimal kilosVivosOriginal) {
        this.kilosVivosOriginal = kilosVivosOriginal;
    }

    public BigDecimal getPorcDesbaste() {
        return porcDesbaste;
    }

    public void setPorcDesbaste(BigDecimal porcDesbaste) {
        this.porcDesbaste = porcDesbaste;
    }
    
    public BigDecimal getKilosVivosReales() {
        return kilosVivosReales;
    }

    public void setKilosVivosReales(BigDecimal kilosVivosReales) {
        this.kilosVivosReales = kilosVivosReales;
    }
    
    public int getDecomisos() {
        return this.decomisos;
    }
    
    public void setDecomisos(int decomisos) {
        this.decomisos = decomisos;
    }
    public short getMediasReces() {
        return this.mediasReces;
    }
    
    public void setMediasReces(short mediasReces) {
        this.mediasReces = mediasReces;
    }
    public int getCabezasFaenadas() {
        return this.cabezasFaenadas;
    }
    
    public void setCabezasFaenadas(int cabezasFaenadas) {
        this.cabezasFaenadas = cabezasFaenadas;
    }
    public int getCabezasMuertas() {
        return this.cabezasMuertas;
    }
    
    public void setCabezasMuertas(int cabezasMuertas) {
        this.cabezasMuertas = cabezasMuertas;
    }
    public BigDecimal getKilosFaenados() {
        return this.kilosFaenados;
    }
    
    public void setKilosFaenados(BigDecimal kilosFaenados) {
        this.kilosFaenados = kilosFaenados;
    }
    public BigDecimal getKilosDecomisados() {
        return this.kilosDecomisados;
    }
    
    public void setKilosDecomisados(BigDecimal kilosDecomisados) {
        this.kilosDecomisados = kilosDecomisados;
    }
    public BigDecimal getRendimiento() {
        return this.rendimiento;
    }
    
    public void setRendimiento(BigDecimal rendimiento) {
        this.rendimiento = rendimiento;
    }
    public BigDecimal getPrecioKiloVivo() {
        return this.precioKiloVivo;
    }

    public BigDecimal getPorcIvaProductor() {
        return porcIvaProductor;
    }

    public void setPorcIvaProductor(BigDecimal porcIvaProductor) {
        this.porcIvaProductor = porcIvaProductor;
    }
    
    public void setPrecioKiloVivo(BigDecimal precioKiloVivo) {
        this.precioKiloVivo = precioKiloVivo;
    }
    public BigDecimal getImporteKiloVivo() {
        return this.importeKiloVivo;
    }

    public BigDecimal getEntregaEfectivoB() {
        return entregaEfectivoB;
    }

    public void setEntregaEfectivoB(BigDecimal entregaEfectivoB) {
        this.entregaEfectivoB = entregaEfectivoB;
    }

    public BigDecimal getImporteKiloVivoImponible() {
        return importeKiloVivoImponible;
    }

    public void setImporteKiloVivoImponible(BigDecimal importeKiloVivoImponible) {
        this.importeKiloVivoImponible = importeKiloVivoImponible;
    }
       
    public BigDecimal getImporteKiloVivoSinIva() {
        return importeKiloVivoSinIva;
    }

    public void setImporteKiloVivoSinIva(BigDecimal importeKiloVivoSinIva) {
        this.importeKiloVivoSinIva = importeKiloVivoSinIva;
    }

    public BigDecimal getIvaKiloVivo() {
        return ivaKiloVivo;
    }

    public void setIvaKiloVivo(BigDecimal ivaKiloVivo) {
        this.ivaKiloVivo = ivaKiloVivo;
    }
    
    public void setImporteKiloVivo(BigDecimal importeKiloVivo) {
        this.importeKiloVivo = importeKiloVivo;
    }
    public BigDecimal getPrecioKiloFaenado() {
        return this.precioKiloFaenado;
    }
    
    public void setPrecioKiloFaenado(BigDecimal precioKiloFaenado) {
        this.precioKiloFaenado = precioKiloFaenado;
    }
    public BigDecimal getImporteFaena() {
        return this.importeFaena;
    }
    
    public void setImporteFaena(BigDecimal importeFaena) {
        this.importeFaena = importeFaena;
    }
    public BigDecimal getPorcIngBrutos() {
        return this.porcIngBrutos;
    }
    
    public void setPorcIngBrutos(BigDecimal porcIngBrutos) {
        this.porcIngBrutos = porcIngBrutos;
    }
    public BigDecimal getValorIngBrutos() {
        return this.valorIngBrutos;
    }
    
    public void setValorIngBrutos(BigDecimal valorIngBrutos) {
        this.valorIngBrutos = valorIngBrutos;
    }
    public BigDecimal getPagoCuentaIva() {
        return this.pagoCuentaIva;
    }
    
    public void setPagoCuentaIva(BigDecimal pagoCuentaIva) {
        this.pagoCuentaIva = pagoCuentaIva;
    }
    public BigDecimal getPorcComision() {
        return this.porcComision;
    }
    
    public void setPorcComision(BigDecimal porcComision) {
        this.porcComision = porcComision;
    }

    public BigDecimal getPorcIvaComisionista() {
        return porcIvaComisionista;
    }

    public void setPorcIvaComisionista(BigDecimal porcIvaComisionista) {
        this.porcIvaComisionista = porcIvaComisionista;
    }

    public BigDecimal getImporteComisionSinIva() {
        return importeComisionSinIva;
    }

    public BigDecimal getEntregaEfectivoComisionB() {
        return entregaEfectivoComisionB;
    }

    public void setEntregaEfectivoComisionB(BigDecimal entregaEfectivoComisionB) {
        this.entregaEfectivoComisionB = entregaEfectivoComisionB;
    }

    public BigDecimal getImporteComisionImponible() {
        return importeComisionImponible;
    }

    public void setImporteComisionImponible(BigDecimal importeComisionImponible) {
        this.importeComisionImponible = importeComisionImponible;
    }
    
    public void setImporteComisionSinIva(BigDecimal importeComisionSinIva) {
        this.importeComisionSinIva = importeComisionSinIva;
    }

    public BigDecimal getIvaComision() {
        return ivaComision;
    }

    public void setIvaComision(BigDecimal ivaComision) {
        this.ivaComision = ivaComision;
    }
    
    public BigDecimal getImporteComision() {
        return this.importeComision;
    }
    
    public void setImporteComision(BigDecimal importeComision) {
        this.importeComision = importeComision;
    }

    public BigDecimal getImporteCostoTotalSinIva() {
        return importeCostoTotalSinIva;
    }

    public void setImporteCostoTotalSinIva(BigDecimal importeCostoTotalSinIva) {
        this.importeCostoTotalSinIva = importeCostoTotalSinIva;
    }
    
    public BigDecimal getImporteCostoTotal() {
        return this.importeCostoTotal;
    }
    
    public void setImporteCostoTotal(BigDecimal importeCostoTotal) {
        this.importeCostoTotal = importeCostoTotal;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Override
    public String toString() {
        return "TropaDet{" + "id=" + id + ", categoria=" + categoria + ", tropa=" + tropa + ", cabezasVivas=" + cabezasVivas + ", cabezasDte=" + cabezasDte + ", kilosVivosOriginal=" + kilosVivosOriginal + ", porcDesbaste=" + porcDesbaste + ", kilosVivos=" + kilosVivos + ", kilosVivosReales=" + kilosVivosReales + ", decomisos=" + decomisos + ", mediasReces=" + mediasReces + ", cabezasFaenadas=" + cabezasFaenadas + ", cabezasMuertas=" + cabezasMuertas + ", kilosFaenados=" + kilosFaenados + ", kilosDecomisados=" + kilosDecomisados + ", rendimiento=" + rendimiento + ", porcIvaProductor=" + porcIvaProductor + ", precioKiloVivo=" + precioKiloVivo + ", importeKiloVivoSinIva=" + importeKiloVivoSinIva + ", entregaEfectivoB=" + entregaEfectivoB + ", importeKiloVivoImponible=" + importeKiloVivoImponible + ", ivaKiloVivo=" + ivaKiloVivo + ", importeKiloVivo=" + importeKiloVivo + ", precioKiloFaenado=" + precioKiloFaenado + ", importeFaena=" + importeFaena + ", porcIngBrutos=" + porcIngBrutos + ", valorIngBrutos=" + valorIngBrutos + ", pagoCuentaIva=" + pagoCuentaIva + ", porcComision=" + porcComision + ", porcIvaComisionista=" + porcIvaComisionista + ", importeComisionSinIva=" + importeComisionSinIva + ", entregaEfectivoComisionB=" + entregaEfectivoComisionB + ", importeComisionImponible=" + importeComisionImponible + ", ivaComision=" + ivaComision + ", importeComision=" + importeComision + ", importeCostoTotalSinIva=" + importeCostoTotalSinIva + ", importeCostoTotal=" + importeCostoTotal + ", observaciones=" + observaciones + '}';
    }
}


