package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TropaDetGarron generated by hbm2java
 */
public class TropaDetGarron  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria= new Categoria();
     private Tropa tropa= new Tropa();
     private int numGarron;
     private String tipo;
     private BigDecimal kilos;
     private Set<InventarioTropa> inventarioTropas = new HashSet<InventarioTropa>(0);

    public TropaDetGarron() {
    }

	
    public TropaDetGarron(Categoria categoria, Tropa tropa, int numGarron, String tipo, BigDecimal kilos) {
        this.categoria = categoria;
        this.tropa = tropa;
        this.numGarron = numGarron;
        this.tipo = tipo;
        this.kilos = kilos;
    }
    public TropaDetGarron(Categoria categoria, Tropa tropa, int numGarron, String tipo, BigDecimal kilos, Set<InventarioTropa> inventarioTropas) {
       this.categoria = categoria;
       this.tropa = tropa;
       this.numGarron = numGarron;
       this.tipo = tipo;
       this.kilos = kilos;
       this.inventarioTropas = inventarioTropas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Tropa getTropa() {
        return this.tropa;
    }
    
    public void setTropa(Tropa tropa) {
        this.tropa = tropa;
    }
    public int getNumGarron() {
        return this.numGarron;
    }
    
    public void setNumGarron(int numGarron) {
        this.numGarron = numGarron;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getKilos() {
        return this.kilos;
    }
    
    public void setKilos(BigDecimal kilos) {
        this.kilos = kilos;
    }
    public Set<InventarioTropa> getInventarioTropas() {
        return this.inventarioTropas;
    }
    
    public void setInventarioTropas(Set<InventarioTropa> inventarioTropas) {
        this.inventarioTropas = inventarioTropas;
    }




}


