package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TropaDet generated by hbm2java
 */
public class TropaDet  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria= new Categoria();
     private Tropa tropa= new Tropa();
     private int cabezasVivas;
     private int cabezasDte;
     private BigDecimal kilosVivos;
     private int decomisos;
     private short mediasReces;
     private int cabezasFaenadas;
     private int cabezasMuertas;
     private BigDecimal kilosFaenados;
     private BigDecimal kilosDecomisados;
     private BigDecimal rendimiento;
     private BigDecimal precioKiloVivo;
     private BigDecimal importeKiloVivo;
     private BigDecimal precioKiloFaenado;
     private BigDecimal importeFaena;
     private BigDecimal porcIngBrutos;
     private BigDecimal valorIngBrutos;
     private BigDecimal pagoCuentaIva;
     private BigDecimal porcComision;
     private BigDecimal importeComision;
     private BigDecimal importeCostoTotal;
     private String observaciones;

    public TropaDet() {
    }

	
    public TropaDet(Categoria categoria, Tropa tropa, int cabezasVivas, int cabezasDte, BigDecimal kilosVivos, int decomisos, short mediasReces, int cabezasFaenadas, int cabezasMuertas, BigDecimal kilosFaenados, BigDecimal kilosDecomisados, BigDecimal rendimiento, BigDecimal precioKiloVivo, BigDecimal importeKiloVivo, BigDecimal precioKiloFaenado, BigDecimal importeFaena, BigDecimal porcIngBrutos, BigDecimal valorIngBrutos, BigDecimal pagoCuentaIva, BigDecimal porcComision, BigDecimal importeComision, BigDecimal importeCostoTotal) {
        this.categoria = categoria;
        this.tropa = tropa;
        this.cabezasVivas = cabezasVivas;
        this.cabezasDte = cabezasDte;
        this.kilosVivos = kilosVivos;
        this.decomisos = decomisos;
        this.mediasReces = mediasReces;
        this.cabezasFaenadas = cabezasFaenadas;
        this.cabezasMuertas = cabezasMuertas;
        this.kilosFaenados = kilosFaenados;
        this.kilosDecomisados = kilosDecomisados;
        this.rendimiento = rendimiento;
        this.precioKiloVivo = precioKiloVivo;
        this.importeKiloVivo = importeKiloVivo;
        this.precioKiloFaenado = precioKiloFaenado;
        this.importeFaena = importeFaena;
        this.porcIngBrutos = porcIngBrutos;
        this.valorIngBrutos = valorIngBrutos;
        this.pagoCuentaIva = pagoCuentaIva;
        this.porcComision = porcComision;
        this.importeComision = importeComision;
        this.importeCostoTotal = importeCostoTotal;
    }
    public TropaDet(Categoria categoria, Tropa tropa, int cabezasVivas, int cabezasDte, BigDecimal kilosVivos, int decomisos, short mediasReces, int cabezasFaenadas, int cabezasMuertas, BigDecimal kilosFaenados, BigDecimal kilosDecomisados, BigDecimal rendimiento, BigDecimal precioKiloVivo, BigDecimal importeKiloVivo, BigDecimal precioKiloFaenado, BigDecimal importeFaena, BigDecimal porcIngBrutos, BigDecimal valorIngBrutos, BigDecimal pagoCuentaIva, BigDecimal porcComision, BigDecimal importeComision, BigDecimal importeCostoTotal, String observaciones) {
       this.categoria = categoria;
       this.tropa = tropa;
       this.cabezasVivas = cabezasVivas;
       this.cabezasDte = cabezasDte;
       this.kilosVivos = kilosVivos;
       this.decomisos = decomisos;
       this.mediasReces = mediasReces;
       this.cabezasFaenadas = cabezasFaenadas;
       this.cabezasMuertas = cabezasMuertas;
       this.kilosFaenados = kilosFaenados;
       this.kilosDecomisados = kilosDecomisados;
       this.rendimiento = rendimiento;
       this.precioKiloVivo = precioKiloVivo;
       this.importeKiloVivo = importeKiloVivo;
       this.precioKiloFaenado = precioKiloFaenado;
       this.importeFaena = importeFaena;
       this.porcIngBrutos = porcIngBrutos;
       this.valorIngBrutos = valorIngBrutos;
       this.pagoCuentaIva = pagoCuentaIva;
       this.porcComision = porcComision;
       this.importeComision = importeComision;
       this.importeCostoTotal = importeCostoTotal;
       this.observaciones = observaciones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Tropa getTropa() {
        return this.tropa;
    }
    
    public void setTropa(Tropa tropa) {
        this.tropa = tropa;
    }
    public int getCabezasVivas() {
        return this.cabezasVivas;
    }
    
    public void setCabezasVivas(int cabezasVivas) {
        this.cabezasVivas = cabezasVivas;
    }
    public int getCabezasDte() {
        return this.cabezasDte;
    }
    
    public void setCabezasDte(int cabezasDte) {
        this.cabezasDte = cabezasDte;
    }
    public BigDecimal getKilosVivos() {
        return this.kilosVivos;
    }
    
    public void setKilosVivos(BigDecimal kilosVivos) {
        this.kilosVivos = kilosVivos;
    }
    public int getDecomisos() {
        return this.decomisos;
    }
    
    public void setDecomisos(int decomisos) {
        this.decomisos = decomisos;
    }
    public short getMediasReces() {
        return this.mediasReces;
    }
    
    public void setMediasReces(short mediasReces) {
        this.mediasReces = mediasReces;
    }
    public int getCabezasFaenadas() {
        return this.cabezasFaenadas;
    }
    
    public void setCabezasFaenadas(int cabezasFaenadas) {
        this.cabezasFaenadas = cabezasFaenadas;
    }
    public int getCabezasMuertas() {
        return this.cabezasMuertas;
    }
    
    public void setCabezasMuertas(int cabezasMuertas) {
        this.cabezasMuertas = cabezasMuertas;
    }
    public BigDecimal getKilosFaenados() {
        return this.kilosFaenados;
    }
    
    public void setKilosFaenados(BigDecimal kilosFaenados) {
        this.kilosFaenados = kilosFaenados;
    }
    public BigDecimal getKilosDecomisados() {
        return this.kilosDecomisados;
    }
    
    public void setKilosDecomisados(BigDecimal kilosDecomisados) {
        this.kilosDecomisados = kilosDecomisados;
    }
    public BigDecimal getRendimiento() {
        return this.rendimiento;
    }
    
    public void setRendimiento(BigDecimal rendimiento) {
        this.rendimiento = rendimiento;
    }
    public BigDecimal getPrecioKiloVivo() {
        return this.precioKiloVivo;
    }
    
    public void setPrecioKiloVivo(BigDecimal precioKiloVivo) {
        this.precioKiloVivo = precioKiloVivo;
    }
    public BigDecimal getImporteKiloVivo() {
        return this.importeKiloVivo;
    }
    
    public void setImporteKiloVivo(BigDecimal importeKiloVivo) {
        this.importeKiloVivo = importeKiloVivo;
    }
    public BigDecimal getPrecioKiloFaenado() {
        return this.precioKiloFaenado;
    }
    
    public void setPrecioKiloFaenado(BigDecimal precioKiloFaenado) {
        this.precioKiloFaenado = precioKiloFaenado;
    }
    public BigDecimal getImporteFaena() {
        return this.importeFaena;
    }
    
    public void setImporteFaena(BigDecimal importeFaena) {
        this.importeFaena = importeFaena;
    }
    public BigDecimal getPorcIngBrutos() {
        return this.porcIngBrutos;
    }
    
    public void setPorcIngBrutos(BigDecimal porcIngBrutos) {
        this.porcIngBrutos = porcIngBrutos;
    }
    public BigDecimal getValorIngBrutos() {
        return this.valorIngBrutos;
    }
    
    public void setValorIngBrutos(BigDecimal valorIngBrutos) {
        this.valorIngBrutos = valorIngBrutos;
    }
    public BigDecimal getPagoCuentaIva() {
        return this.pagoCuentaIva;
    }
    
    public void setPagoCuentaIva(BigDecimal pagoCuentaIva) {
        this.pagoCuentaIva = pagoCuentaIva;
    }
    public BigDecimal getPorcComision() {
        return this.porcComision;
    }
    
    public void setPorcComision(BigDecimal porcComision) {
        this.porcComision = porcComision;
    }
    public BigDecimal getImporteComision() {
        return this.importeComision;
    }
    
    public void setImporteComision(BigDecimal importeComision) {
        this.importeComision = importeComision;
    }
    public BigDecimal getImporteCostoTotal() {
        return this.importeCostoTotal;
    }
    
    public void setImporteCostoTotal(BigDecimal importeCostoTotal) {
        this.importeCostoTotal = importeCostoTotal;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


