package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TropaViaje generated by hbm2java
 */
public class TropaViaje  implements java.io.Serializable {


     private Integer id;
     private Tropa tropa;
     private Viaje viaje;
     private BigDecimal porcAfectado;
     private BigDecimal valorAfectado;

    public TropaViaje() {
    }

    public TropaViaje(Tropa tropa, Viaje viaje, BigDecimal porcAfectado, BigDecimal valorAfectado) {
       this.tropa = tropa;
       this.viaje = viaje;
       this.porcAfectado = porcAfectado;
       this.valorAfectado = valorAfectado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tropa getTropa() {
        return this.tropa;
    }
    
    public void setTropa(Tropa tropa) {
        this.tropa = tropa;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public BigDecimal getPorcAfectado() {
        return this.porcAfectado;
    }
    
    public void setPorcAfectado(BigDecimal porcAfectado) {
        this.porcAfectado = porcAfectado;
    }
    public BigDecimal getValorAfectado() {
        return this.valorAfectado;
    }
    
    public void setValorAfectado(BigDecimal valorAfectado) {
        this.valorAfectado = valorAfectado;
    }




}


