package entidades;
// Generated 11 dic. 2021 10:22:32 by Hibernate Tools 4.3.1



/**
 * UnidadNegocioGasto generated by hbm2java
 */
public class UnidadNegocioGasto  implements java.io.Serializable {

     private Integer id;
     private TipoGasto tipoGasto;
     private UnidadNegocio unidadNegocio;
     private Integer plantilla;
     private  Integer orden;
    
    public UnidadNegocioGasto() {
    }

	
    public UnidadNegocioGasto(TipoGasto tipoGasto, UnidadNegocio unidadNegocio) {
        this.tipoGasto = tipoGasto;
        this.unidadNegocio = unidadNegocio;
    }
    public UnidadNegocioGasto(TipoGasto tipoGasto, UnidadNegocio unidadNegocio, Integer plantilla) {
       this.tipoGasto = tipoGasto;
       this.unidadNegocio = unidadNegocio;
       this.plantilla = plantilla;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoGasto getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(TipoGasto tipoGasto) {
        this.tipoGasto = tipoGasto;
    }
    public UnidadNegocio getUnidadNegocio() {
        return this.unidadNegocio;
    }
    
    public void setUnidadNegocio(UnidadNegocio unidadNegocio) {
        this.unidadNegocio = unidadNegocio;
    }
    public Integer getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Integer plantilla) {
        this.plantilla = plantilla;
    }

    public Integer getOrden() {
        return orden;
    }

    public void setOrden(Integer orden) {
        this.orden = orden;
    }

}


