package entidades;
// Generated 11 dic. 2021 10:22:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadNegocio generated by hbm2java
 */
public class UnidadNegocio  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<UnidadNegocioGasto> unidadNegocioGastos = new HashSet<UnidadNegocioGasto>(0);

    public UnidadNegocio() {
    }

	
    public UnidadNegocio(String nombre) {
        this.nombre = nombre;
    }
    public UnidadNegocio(String nombre, Set<UnidadNegocioGasto> unidadNegocioGastos) {
       this.nombre = nombre;
       this.unidadNegocioGastos = unidadNegocioGastos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<UnidadNegocioGasto> getUnidadNegocioGastos() {
        return this.unidadNegocioGastos;
    }
    
    public void setUnidadNegocioGastos(Set<UnidadNegocioGasto> unidadNegocioGastos) {
        this.unidadNegocioGastos = unidadNegocioGastos;
    }




}


