package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioCliente generated by hbm2java
 */
public class UsuarioCliente  implements java.io.Serializable {


     private Integer id;
     private String nombreUsuario;
     private String clave;
     private String apellido;
     private String nombre;
     private Date fecha;
     private char estado;
     private Set<DireccionUsuarioCliente> direccionUsuarioClientes = new HashSet<DireccionUsuarioCliente>(0);

    public UsuarioCliente() {
    }

	
    public UsuarioCliente(String nombreUsuario, String clave, String apellido, String nombre, Date fecha, char estado) {
        this.nombreUsuario = nombreUsuario;
        this.clave = clave;
        this.apellido = apellido;
        this.nombre = nombre;
        this.fecha = fecha;
        this.estado = estado;
    }
    public UsuarioCliente(String nombreUsuario, String clave, String apellido, String nombre, Date fecha, char estado, Set<DireccionUsuarioCliente> direccionUsuarioClientes) {
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fecha = fecha;
       this.estado = estado;
       this.direccionUsuarioClientes = direccionUsuarioClientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<DireccionUsuarioCliente> getDireccionUsuarioClientes() {
        return this.direccionUsuarioClientes;
    }
    
    public void setDireccionUsuarioClientes(Set<DireccionUsuarioCliente> direccionUsuarioClientes) {
        this.direccionUsuarioClientes = direccionUsuarioClientes;
    }




}


