package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VentaEstancia generated by hbm2java
 */
public class VentaEstancia  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private LocalCarniceria localCarniceria;
     private Date fecCarga;
     private Date fecMov;
     private int idUsuario;
     private String tipoCompro;
     private String puntoVenta;
     private String numFact;
     private String tipoFact;
     private BigDecimal subtotalSinIva;
     private BigDecimal porcIva;
     private BigDecimal valorIva;
     private BigDecimal valorTotal;
     private String observaciones;
     private Set<VentaEstanciaDet> ventaEstanciaDets = new HashSet<VentaEstanciaDet>(0);
     private Set<VentaEstanciaRemito> ventaEstanciaRemitos = new HashSet<VentaEstanciaRemito>(0);

    public VentaEstancia() {
    }

	
    public VentaEstancia(Date fecCarga, Date fecMov, int idUsuario, BigDecimal subtotalSinIva, BigDecimal valorIva, BigDecimal valorTotal) {
        this.fecCarga = fecCarga;
        this.fecMov = fecMov;
        this.idUsuario = idUsuario;
        this.subtotalSinIva = subtotalSinIva;
        this.valorIva = valorIva;
        this.valorTotal = valorTotal;
    }
    public VentaEstancia(Cliente cliente, LocalCarniceria localCarniceria, Date fecCarga, Date fecMov, int idUsuario, String tipoCompro, String puntoVenta, String numFact, String tipoFact, BigDecimal subtotalSinIva, BigDecimal porcIva, BigDecimal valorIva, BigDecimal valorTotal, String observaciones, Set<VentaEstanciaDet> ventaEstanciaDets, Set<VentaEstanciaRemito> ventaEstanciaRemitos) {
       this.cliente = cliente;
       this.localCarniceria = localCarniceria;
       this.fecCarga = fecCarga;
       this.fecMov = fecMov;
       this.idUsuario = idUsuario;
       this.tipoCompro = tipoCompro;
       this.puntoVenta = puntoVenta;
       this.numFact = numFact;
       this.tipoFact = tipoFact;
       this.subtotalSinIva = subtotalSinIva;
       this.porcIva = porcIva;
       this.valorIva = valorIva;
       this.valorTotal = valorTotal;
       this.observaciones = observaciones;
       this.ventaEstanciaDets = ventaEstanciaDets;
       this.ventaEstanciaRemitos = ventaEstanciaRemitos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getTipoCompro() {
        return this.tipoCompro;
    }
    
    public void setTipoCompro(String tipoCompro) {
        this.tipoCompro = tipoCompro;
    }
    public String getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(String puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    public String getNumFact() {
        return this.numFact;
    }
    
    public void setNumFact(String numFact) {
        this.numFact = numFact;
    }
    public String getTipoFact() {
        return this.tipoFact;
    }
    
    public void setTipoFact(String tipoFact) {
        this.tipoFact = tipoFact;
    }
    public BigDecimal getSubtotalSinIva() {
        return this.subtotalSinIva;
    }
    
    public void setSubtotalSinIva(BigDecimal subtotalSinIva) {
        this.subtotalSinIva = subtotalSinIva;
    }
    public BigDecimal getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(BigDecimal porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<VentaEstanciaDet> getVentaEstanciaDets() {
        return this.ventaEstanciaDets;
    }
    
    public void setVentaEstanciaDets(Set<VentaEstanciaDet> ventaEstanciaDets) {
        this.ventaEstanciaDets = ventaEstanciaDets;
    }
    public Set<VentaEstanciaRemito> getVentaEstanciaRemitos() {
        return this.ventaEstanciaRemitos;
    }
    
    public void setVentaEstanciaRemitos(Set<VentaEstanciaRemito> ventaEstanciaRemitos) {
        this.ventaEstanciaRemitos = ventaEstanciaRemitos;
    }




}


