package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer id;
     private LocalCarniceria localCarniceria;
     private Persona persona;
     private int idUsuario;
     private Date fecMov;
     private Date fecCarga;
     private char estado;
     private BigDecimal valorTotal;
     private BigDecimal porcDesc;
     private BigDecimal valorDesc;
     private BigDecimal valorFinal;
     private BigDecimal porcIva;
     private BigDecimal valorIva;
     private BigDecimal valorSiva;
     private char pagado;
     private char tipoComprobante;
     private String condIva;
     private String tipoFactura;
     private String puntoVenta;
     private String numFactura;
     private String observaciones;
     private Set<VentaCc> ventaCcs = new HashSet<VentaCc>(0);
     private Set<VentaDet> ventaDets = new HashSet<VentaDet>(0);

    public Venta() {
    }

	
    public Venta(LocalCarniceria localCarniceria, int idUsuario, Date fecMov, Date fecCarga, char estado, BigDecimal valorTotal, BigDecimal porcDesc, BigDecimal valorDesc, BigDecimal valorFinal, BigDecimal porcIva, BigDecimal valorIva, BigDecimal valorSiva, char pagado, char tipoComprobante) {
        this.localCarniceria = localCarniceria;
        this.idUsuario = idUsuario;
        this.fecMov = fecMov;
        this.fecCarga = fecCarga;
        this.estado = estado;
        this.valorTotal = valorTotal;
        this.porcDesc = porcDesc;
        this.valorDesc = valorDesc;
        this.valorFinal = valorFinal;
        this.porcIva = porcIva;
        this.valorIva = valorIva;
        this.valorSiva = valorSiva;
        this.pagado = pagado;
        this.tipoComprobante = tipoComprobante;
    }
    public Venta(LocalCarniceria localCarniceria, Persona persona, int idUsuario, Date fecMov, Date fecCarga, char estado, BigDecimal valorTotal, BigDecimal porcDesc, BigDecimal valorDesc, BigDecimal valorFinal, BigDecimal porcIva, BigDecimal valorIva, BigDecimal valorSiva, char pagado, char tipoComprobante, String condIva, String tipoFactura, String puntoVenta, String numFactura, String observaciones, Set<VentaCc> ventaCcs, Set<VentaDet> ventaDets) {
       this.localCarniceria = localCarniceria;
       this.persona = persona;
       this.idUsuario = idUsuario;
       this.fecMov = fecMov;
       this.fecCarga = fecCarga;
       this.estado = estado;
       this.valorTotal = valorTotal;
       this.porcDesc = porcDesc;
       this.valorDesc = valorDesc;
       this.valorFinal = valorFinal;
       this.porcIva = porcIva;
       this.valorIva = valorIva;
       this.valorSiva = valorSiva;
       this.pagado = pagado;
       this.tipoComprobante = tipoComprobante;
       this.condIva = condIva;
       this.tipoFactura = tipoFactura;
       this.puntoVenta = puntoVenta;
       this.numFactura = numFactura;
       this.observaciones = observaciones;
       this.ventaCcs = ventaCcs;
       this.ventaDets = ventaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }
    public BigDecimal getPorcDesc() {
        return this.porcDesc;
    }
    
    public void setPorcDesc(BigDecimal porcDesc) {
        this.porcDesc = porcDesc;
    }
    public BigDecimal getValorDesc() {
        return this.valorDesc;
    }
    
    public void setValorDesc(BigDecimal valorDesc) {
        this.valorDesc = valorDesc;
    }
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }
    
    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }
    public BigDecimal getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(BigDecimal porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }
    public BigDecimal getValorSiva() {
        return this.valorSiva;
    }
    
    public void setValorSiva(BigDecimal valorSiva) {
        this.valorSiva = valorSiva;
    }
    public char getPagado() {
        return this.pagado;
    }
    
    public void setPagado(char pagado) {
        this.pagado = pagado;
    }
    public char getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(char tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }
    public String getCondIva() {
        return this.condIva;
    }
    
    public void setCondIva(String condIva) {
        this.condIva = condIva;
    }
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public String getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(String puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    public String getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(String numFactura) {
        this.numFactura = numFactura;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<VentaCc> getVentaCcs() {
        return this.ventaCcs;
    }
    
    public void setVentaCcs(Set<VentaCc> ventaCcs) {
        this.ventaCcs = ventaCcs;
    }
    public Set<VentaDet> getVentaDets() {
        return this.ventaDets;
    }
    
    public void setVentaDets(Set<VentaDet> ventaDets) {
        this.ventaDets = ventaDets;
    }




}


