package entidades;
// Generated 8 oct. 2022 10:23:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VentaDet generated by hbm2java
 */
public class VentaDet  implements java.io.Serializable {


     private Integer id;
     private Producto producto;
     private Unidad unidad;
     private Venta venta;
     private BigDecimal cantidad;
     private BigDecimal precioUnitario;
     private BigDecimal valorAdicional;
     private BigDecimal precioTotal;
     private char estado;
     private String observacion;

    public VentaDet() {
    }

	
    public VentaDet(Producto producto, Unidad unidad, Venta venta, BigDecimal cantidad, BigDecimal precioUnitario, BigDecimal valorAdicional, BigDecimal precioTotal, char estado) {
        this.producto = producto;
        this.unidad = unidad;
        this.venta = venta;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.valorAdicional = valorAdicional;
        this.precioTotal = precioTotal;
        this.estado = estado;
    }
    public VentaDet(Producto producto, Unidad unidad, Venta venta, BigDecimal cantidad, BigDecimal precioUnitario, BigDecimal valorAdicional, BigDecimal precioTotal, char estado, String observacion) {
       this.producto = producto;
       this.unidad = unidad;
       this.venta = venta;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.valorAdicional = valorAdicional;
       this.precioTotal = precioTotal;
       this.estado = estado;
       this.observacion = observacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public BigDecimal getValorAdicional() {
        return this.valorAdicional;
    }
    
    public void setValorAdicional(BigDecimal valorAdicional) {
        this.valorAdicional = valorAdicional;
    }
    public BigDecimal getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(BigDecimal precioTotal) {
        this.precioTotal = precioTotal;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


