package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private Integer id;
     private Chofer chofer= new Chofer();
     private Cliente cliente= new Cliente();
     private Comisionista comisionista= new Comisionista();
     private Localidad localidadByIdOrigen= new Localidad();
     private Localidad localidadByIdDestino= new Localidad();
     private VehiculoFlete vehiculoFlete= new VehiculoFlete();
     private Date fecMov;
     private Date fecCarga;
     private char tipoProducto;
     private String unidadesTransportadas;
     private String obsOrigen;
     private String obsDestino;
     private BigDecimal distancia;
     private BigDecimal cantidad;
     private BigDecimal valorNeto;
     private BigDecimal porcIva;
     private BigDecimal valorIva;
     private BigDecimal valorTotal;
     private Character tipoJaula;
     private char procesado;
     private Set<LiquidacionViaje> liquidacionViajes = new HashSet<LiquidacionViaje>(0);
     private Set<TropaViaje> tropaViajes = new HashSet<TropaViaje>(0);

    public Viaje() {
    }

	
    public Viaje(Chofer chofer, Cliente cliente, Localidad localidadByIdOrigen, Localidad localidadByIdDestino, VehiculoFlete vehiculoFlete, Date fecMov, Date fecCarga, char tipoProducto, char procesado) {
        this.chofer = chofer;
        this.cliente = cliente;
        this.localidadByIdOrigen = localidadByIdOrigen;
        this.localidadByIdDestino = localidadByIdDestino;
        this.vehiculoFlete = vehiculoFlete;
        this.fecMov = fecMov;
        this.fecCarga = fecCarga;
        this.tipoProducto = tipoProducto;
        this.procesado = procesado;
    }
    public Viaje(Chofer chofer, Cliente cliente, Comisionista comisionista, Localidad localidadByIdOrigen, Localidad localidadByIdDestino, VehiculoFlete vehiculoFlete, Date fecMov, Date fecCarga, char tipoProducto, String unidadesTransportadas, String obsOrigen, String obsDestino, BigDecimal distancia, BigDecimal cantidad, BigDecimal valorNeto, BigDecimal porcIva, BigDecimal valorIva, BigDecimal valorTotal, Character tipoJaula, char procesado, Set<LiquidacionViaje> liquidacionViajes, Set<TropaViaje> tropaViajes) {
       this.chofer = chofer;
       this.cliente = cliente;
       this.comisionista = comisionista;
       this.localidadByIdOrigen = localidadByIdOrigen;
       this.localidadByIdDestino = localidadByIdDestino;
       this.vehiculoFlete = vehiculoFlete;
       this.fecMov = fecMov;
       this.fecCarga = fecCarga;
       this.tipoProducto = tipoProducto;
       this.unidadesTransportadas = unidadesTransportadas;
       this.obsOrigen = obsOrigen;
       this.obsDestino = obsDestino;
       this.distancia = distancia;
       this.cantidad = cantidad;
       this.valorNeto = valorNeto;
       this.porcIva = porcIva;
       this.valorIva = valorIva;
       this.valorTotal = valorTotal;
       this.tipoJaula = tipoJaula;
       this.procesado = procesado;
       this.liquidacionViajes = liquidacionViajes;
       this.tropaViajes = tropaViajes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Comisionista getComisionista() {
        return this.comisionista;
    }
    
    public void setComisionista(Comisionista comisionista) {
        this.comisionista = comisionista;
    }
    public Localidad getLocalidadByIdOrigen() {
        return this.localidadByIdOrigen;
    }
    
    public void setLocalidadByIdOrigen(Localidad localidadByIdOrigen) {
        this.localidadByIdOrigen = localidadByIdOrigen;
    }
    public Localidad getLocalidadByIdDestino() {
        return this.localidadByIdDestino;
    }
    
    public void setLocalidadByIdDestino(Localidad localidadByIdDestino) {
        this.localidadByIdDestino = localidadByIdDestino;
    }
    public VehiculoFlete getVehiculoFlete() {
        return this.vehiculoFlete;
    }
    
    public void setVehiculoFlete(VehiculoFlete vehiculoFlete) {
        this.vehiculoFlete = vehiculoFlete;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public char getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(char tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public String getUnidadesTransportadas() {
        return this.unidadesTransportadas;
    }
    
    public void setUnidadesTransportadas(String unidadesTransportadas) {
        this.unidadesTransportadas = unidadesTransportadas;
    }
    public String getObsOrigen() {
        return this.obsOrigen;
    }
    
    public void setObsOrigen(String obsOrigen) {
        this.obsOrigen = obsOrigen;
    }
    public String getObsDestino() {
        return this.obsDestino;
    }
    
    public void setObsDestino(String obsDestino) {
        this.obsDestino = obsDestino;
    }
    public BigDecimal getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(BigDecimal distancia) {
        this.distancia = distancia;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getValorNeto() {
        return this.valorNeto;
    }
    
    public void setValorNeto(BigDecimal valorNeto) {
        this.valorNeto = valorNeto;
    }
    public BigDecimal getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(BigDecimal porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Character getTipoJaula() {
        return this.tipoJaula;
    }
    
    public void setTipoJaula(Character tipoJaula) {
        this.tipoJaula = tipoJaula;
    }
    public char getProcesado() {
        return this.procesado;
    }
    
    public void setProcesado(char procesado) {
        this.procesado = procesado;
    }
    public Set<LiquidacionViaje> getLiquidacionViajes() {
        return this.liquidacionViajes;
    }
    
    public void setLiquidacionViajes(Set<LiquidacionViaje> liquidacionViajes) {
        this.liquidacionViajes = liquidacionViajes;
    }
    public Set<TropaViaje> getTropaViajes() {
        return this.tropaViajes;
    }
    
    public void setTropaViajes(Set<TropaViaje> tropaViajes) {
        this.tropaViajes = tropaViajes;
    }




}


