package general;
// Generated 23/04/2021 14:52:05 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Asiento generated by hbm2java
 */
@XmlRootElement (name = "asiento")
public class Asiento  implements java.io.Serializable {
     private int id;
     private int idEmpresa;
     private int numPlantilla;
     private String fecMov;
     private Date fecCarga;
     private int idUsuario;
     private int idCentroCosto;
     private String descripcion;
     private ArrayList<ParametroAsiento> listaPar= new ArrayList<ParametroAsiento>();
     private ArrayList<AsientoCuentaAdicional> listaCuentasAdic= new ArrayList<AsientoCuentaAdicional>();

    public Asiento() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdEmpresa() {
        return idEmpresa;
    }

    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    public int getNumPlantilla() {
        return numPlantilla;
    }

    public void setNumPlantilla(int numPlantilla) {
        this.numPlantilla = numPlantilla;
    }

    public String getFecMov() {
        return fecMov;
    }

    public void setFecMov(String fecMov) {
        this.fecMov = fecMov;
    }

    public Date getFecCarga() {
        return fecCarga;
    }

    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public int getIdCentroCosto() {
        return idCentroCosto;
    }

    public void setIdCentroCosto(int idCentroCosto) {
        this.idCentroCosto = idCentroCosto;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public ArrayList<ParametroAsiento> getListaPar() {
        return listaPar;
    }

    public void setListaPar(ArrayList<ParametroAsiento> listaPar) {
        this.listaPar = listaPar;
    }

    public ArrayList<AsientoCuentaAdicional> getListaCuentasAdic() {
        return listaCuentasAdic;
    }

    public void setListaCuentasAdic(ArrayList<AsientoCuentaAdicional> listaCuentasAdic) {
        this.listaCuentasAdic = listaCuentasAdic;
    }
    
    
}


